- NetworkTwoDLayer.py
If coming from a conv2 layer then sizes is in the right format for the mdlstm layer [[h1,w1],[h2,w2],...] but if coming from s 1Dto2D layer then the sizes are laid out as [[h1,h2,...],[w1,w2,...]] which will results in corrupted output and gradients from the mdlstm layer.
> Fix 1Dto2D layer to MDLSTM layer sizes layout issue

- TFUtil.py
- tests/test_TFUtil.py
Calling `windowed_nd` in `TFUtil.py` with `source=[[[1]], [[2]], [[3]]]`, `window='valid'`, `window_size=2`, `time_axis=0` and `new_window_axis=1` results in the following error:
ValueError: Cannot reshape a tensor with 8 elements to shape [2,5,1,1] (10 elements) for 'windowed_batch/Reshape_1' (op: 'Reshape') with input shapes: [8], [4] and with input tensors computed as partial shapes: input[1] = [2,5,1,1].
The expected result would be `[[[[1]], [[2]]], [[[2]], [[3]]]]`
The reason for this is that the final reshaping does not consider the smaller size of the tensor due to the missing padding.
> Fix windowed_nd in TFUtil for padding valid

- TFNetworkLayer.py
I think that this is generally needed fix, but I'm not sure if it is the right way to do it (Especially in the WindowLayer)
It seems like in both cases some inconsistencies with the feature_dim_axis occur in the current implementation
@albertz could you take a look?
> fix feature_dim_axis in MergeDimsLayer and WindowLayer

- Dataset.py
- LmDataset.py
The index offset due to partition_epoch was still added in _get_line_nr(). This is wrong, as partition_epoch is now handled by get_sequence_order_for_epoch() and thus self._seq_order contains only elements for the current sub-epoch.
> fix: partition_epoch in TranslationDataset

- LmDataset.py
- MetaDataset.py
- TFEngine.py
- TFNetworkLayer.py
Should rather be 3 separate PRs...
I forgot some last changes to the CN dataset that were necessary for the ensembling experiments, this is the first commit.
Then I solved a crash occurring when max_seq_length is set in search. Translations for the filtered sentences were expected, causing a key error in out_cache. With this solution the filtered sentences do not appear in the output at all. Maybe we should add some line or enforce max_seq_length=0 instead? You might want to check this (although I have), an error here would be critical ;) 
Finally, get_dep_layers had to be implemented for the SwitchLayer to be able to use it in a recurrent unit.
> some more misc. fixes

- TFNetworkRecLayer.py
Fixes include:
1. Class name changed from "LayerNormLSTMCell" to "LayerNormVariantsLSTMCell" just to make sure not to face override problems with TF official implementation.
2. Removed tf.nn.dropout and use Returnn dropout implementation for speedup.
3. Added "name" param to "_norm" function to create different TF variables.
4. In "_linear" function, the bias is not added if there is layer norm. In addition, "var_creation_scope()" is used when creating the bias.
5. Added overview descriptions about different LSTM layer norm variants.
> LayerNormVariantsLSTMCell

- MetaDataset.py
iteritems() -> items()
num_seqs was unset because of `self._num_seqs = None` in `CachedDataset2.init_seq_order()`.
data type of empty array has to be set to make assert in `CombinedDataset.get_data_dtype()` work.
I thought about partition_epoch for CombinedDataset, but I think this should be done by the sub-datasets, thus the assert.
> small changes to make CombinedDataset work again

- TFEngine.py
- TFNetwork.py
This change is necessary in order to use the trainable option for freezing certain layers
while still being able to load the corresponding parameters in the checkpoint.
I don't see any problems occurring due to this change. Please let me know if there are. Then I have to find another solution.
> Changed CustomCheckpointLoader call to look for all params (not only trainable)

- CachedDataset2.py
- MetaDataset.py
1. Get data dims from the sub-datasets instead of explicitly giving it in the config. This is straight forward and I don't know why it hasn't been this way all along 😄 
2. When we combine datasets of the same (or similar) type, it might be straight forward to see which sequences correspond. For example when combining two TranslationDatasets most likely "line-n" of dataset A belongs to "line-n" of dataset B.
For this purpose, I implemented reading the list of sequence tags from one dataset (the one containing the "data" feature) and applying it to all others. In this case a sequence list created by the user is no longer necessary.
> Easier configuration of MetaDataset

- TFUtil.py
I got an `unexpected type <class 'numpy.int64'>` when using MergeDimLayer inside the recurrent unit.
The numpy type comes from line 2614 in TFNetworkLayer:
`res_dim = numpy.prod([data.batch_shape[i] for i in axes])`
An alternative fix would be to convert to int here right away.
> Fix unexpected type in _get_control_flow_ops

- NativeOp.cpp
- NativeOp.py
- TFNativeOp.py
- TFNetwork.py
- TFNetworkRecLayer.py
I've added support for a onedirectional 2D-LSTM in TensorFlow.
The code is based on the Theano implementation for 4 directions, and is not as general as I would like. But it might be helpful nevertheless.
The inputs to the 2D-LSTM layer have to be two sequences (eg. source and target). The output is a sequence, not a 2D grid, so it can easily be combined with other layers.
During inference, it is assumed that the shape of the second (target) dimension is always 1 (the previous target word).
This might be relevant for issue #8.
> Added onedirectional 2D-LSTM

- Dataset.py
- MetaDataset.py
The current implementation of CombinedDataset lacks the ability to jointly sort all sequences using seq orders that depend on the length of the sequences ('sorted' and 'laplace'). The concrete use case where we need this is the dynamic combination of bilingual corpora (instead of concatenating the text files) for training multi-lingual MT systems.
I changed the calculation of the sequence order such that it uses the "standard" LayerBase.get_seq_order_for_epoch() and applies it to the set of all sequences. However, I kept the old behaviour as a special case, which is still the default.
At the same time I adopted reading data dims from data as in 5851c19 and did some renaming (if you insist, I can still make those separate commits). 
I also added a repeat_epoch option to Dataset, such that …
> CombinedDataset: redesign to support all seq ordering options

- TFNetwork.py
- TFNetworkLayer.py
- TFNetworkRecLayer.py
This is needed for [Factored NMT](https://arxiv.org/abs/1609.04621).
ChoiceLayer now accepts two sources and two corresponding targets (e.g. target factors) and does a joint decision for both. Criterion is the sum of the two incoming scores in log space. Beam pruning is applied to both sources to reduce the number of possible combinations.
As the layer has several outputs (labels for both targets), I used sub-layers to refer to them. For this I also needed sub-layer templates.
An example config can be found here: https://github.com/patrick-wilken/returnn-examples/blob/master/factored-nmt/config
> ChoiceLayer: multiple targets (factors)

- NativeOp.cpp
TensorFlow 1.4 does not provide the necessary functions to run the 2D-LSTM code. This PR disables the relevant code and displays an error message if the TF version is not supported.
Fixes #115
> Disable 2DLSTM code for TF <= 1.4

- TFNativeOp.py
- tools/compile_native_op.py
When we use TF with Intel MKL (built with `--config=mkl`) and build native ops, OpMaker retrieves both OpenBLAS and MKL from the run-time environment, such that libopenblas has a higher priority.
With `--blas_lib` we can specify either
* `/path/to/libmyblas.so` -> link with `-L/path/to -lmyblas`, or
* `libmyblas.so` -> perform search and add `-L... -l...` for library that contains `libmyblas.so` in file name
> adding flag to tools/compile_native_op.py to better control linker param

- TFNetworkLayer.py
It would be really helpful for beginners, if during debugging the axis information would not be dropped for some cases, as this can be very confusing without looking directly into the code.
I also ran in some issue with ConvLayer, an assert seems more helpful than:
`TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'`
> dataset description and ConvLayer assert

- LmDataset.py
- tools/hdf_dump.py
Set "classes" to be the target key after conversion, when the
original dataset uses 'data' as the target key (which is reserved
to be the input key for the HDFDataset).
Add 'labels["delayed"]' in LmDataset.
These fix bug for converting LmDataset to HDFDataset.
> hdf-dump, fix bug: converting dataset with 'data' as target key

- LearningRateControl.py
Add 'newbob_relative_error_old_minus_new' option.
If 'newbob_relative_error_old_minus_new' is set to True, compute
relative error as (old - new) / old.
Otherwise (by default), (new - old) / new is used as before.
I would like to have an option to compute the relative change in this
direction and use positive valued lower-bound threshold (isn't this more natural?).
What do you think @albertz ?
This behavior can not be reproduced by the default code, even if you
try to fit the threshold.
Also, in line 176, 
```relativeError = (newError - oldError) / abs(newError)```
I think it is not correct to have "abs" in the denominator in the general case.
> LearningRateControl, alternative relative error

- TFNetwork.py
- TFNetworkLayer.py
- TFNetworkRecLayer.py
- tests/test_TFNetworkLayer.py
- tests/test_TFNetworkRecLayer.py
This PR:
- allows to set `trainable=False` to layers that are part of a `RecLayer` 
- adds test cases to ensure that both trainable and untrainable layers are handled correctly, whether they were optimized out of the loop or not
This fixes #117
> Respect trainable=False for RecLayer subnetwork layers

- TFNetworkLayer.py
- TFUtil.py
- tests/test_TFNetworkLayer.py
When seq_lens are equal, possible faster computation with masked_time=False.
Some modifications in TFUtil.py, which fix bugs and extend the functionality.
See #88 for previous conversations.
> TFNetworkLayer.py added flag masked_time to BatchNorm layer

- TFNetworkLayer.py
- TFNetworkRecLayer.py
Used keys is currently lacking any target that was specified in layers of the subnetwork. The subnetwork copies all targets from the parent network, and adds the defined target, but no additional targets.
> add all layer targets to used_data_keys in SubnetworkRecCell

- SprintControl.py
When building RASR with Python 3, the segment name is encoded as bytes, so we need to decode it into string. It is not guaranteed, but in 100% of corpus files I've worked with, the segment name is pure ascii.
This PR should allow to keep using RASR binaries built with Python 2 as well as to switch to Python 3.
> SprintControl.py: convert segment name from bytes to string

- TFNetworkRecLayer.py
- tests/test_TFNetworkRecLayer.py
Support for static time axis in the `GenericAttentionLayer`.
See https://github.com/rwth-i6/returnn/commit/2da3644#r33196068 and further discussion.
> Fix for static time-axis in generic_att

- TFNetworkRecLayer.py
Simply concatenating the output of this layer to any other layer did not work, so this seems to fix all issues related to using positional encoding as concatenation and not additive.
> fixed batch dimension crash in PositionalEncodingLayer for add_to_input=False

- TFNetworkLayer.py
I am not sure why the code was written like this before, but i checked all tensorflow versions from 1.8 to 1.13, and it has always been that constant_value is assumed to be 0 by default, and it is only used when the mode is "CONSTANT", but also accepts every value given.
> removed unnecessary constraints on PaddingLayer

- tools/hdf_dump_translation_dataset.py
When using huge MT corpora (100M + lines) hdf_dump.py becomes unusable because of memory usage and run time.
This script is much faster (e.g. in my tests factor >30 on 7M lines) and uses only a fraction of the memory (e.g. 0.6 vs. 9GB on 7M sentences). The output HDF file contains exactly the same data.
The issue with hdf_dump.py is that it accesses the file for every sequence, which is slow. Also, it uses TranslationDataset, which loads the whole corpus into memory.
hdf_dump could be improved by buffering as in this script. But TranlsationDataset as implemented now cannot be used for that large amounts of data.
I realize a generic solution to create HDF files is more desirable, but I think this special solution is worth sharing.
> Efficient HDF creation tool for TranslationDatasets

- CachedDataset.py
dict[int, int] self._seq_index_inv gets huge and creation is slow when used on large amounts of sequences (100M). So just create it if we really need it. For the case of disabled cache, reinitialization is cheaper, so never map indices here.
> CachedDataset: save index inversion

- TFNetworkLayer.py
- tests/test_TFNetworkLayer.py
As previously mention in PR #179, the HDFDumpLayer expected the time dimension to be a sequence of variable length, ie. `size_placeholder` had to be set.
This PR makes the input requirements (a sequence, not a single state; only one input, not multiple) explicit and allows the sequence length to be fixed.
If the dump layer is supposed to be able to handle an input that is only a single state and not a whole sequence, this is yet another issue. For now, a simple workaround is to first pass the individual state through the `expand_dims` layer, and then dump it afterwards. This approach is used in my test case.
> Bugfix for HDFDumpLayer: Support for sequences of fixed length

- GeneratingDataset.py
I am not sure if this is too slow, but I think applying the vocabulary to the whole dataset should be ok.
> added correct sorting for targets only mode in OggZipDataset

- CachedDataset.py
- HDFDataset.py
We had trouble using the HDFDataset on large amounts of sequences as experiments needed too much RAM. (The most extreme was >60 GB on 500M sequences.)
This is because the dataset stores many data structures of O(total number of sequences): sequence lengths, sequence tags, file index for each sequence, and start index for each sequence within the file. Note, that we don't use the cache, so the memory is consumed by this "meta data" only.
With the provided changes I managed to reduce that substantially. I realize that some of the changes might be controversial in terms of design decisions and speed performance, so let's discuss.
...by the way, you could even go one step further and remove the last O(total number of sequences) object `self.file_seq_start` by storing this information in the …
> Reduced memory consumption of HDFDataset

- TFNetworkLayer.py
- TFUtil.py
I propose the following changes to the `sampling_loss`:
* Add `log_norm_factor` to `sampling_loss` for nce; this is fixed to 0.0 in the standard TensorFlow implementation. However, we found that this is worth tuning for Noise Contrastive Estimation.
* As result, it is required to also include `compute_sampled_logits` and `sum_rows` separately, as this is an implementation detail in TensorFlow and not part of the public API. These functions are mostly copied from there. See comments in the doc-string.
> nce: add log_norm_factor for nce

- tools/bliss-to-ogg-zip.py
Previously, `duration=None` was written into the `dest_meta_file`. This is fixed in this commit.
> bliss-to-ogg-zip: fix duration

- TFUtil.py
- tests/test_TFNetworkLayer.py
- tests/test_TFUtil.py
test Data.get_common_data for two sources with equal shape. Expecting to get the same shape. 
The behavior is required by CombineLayer with param `kind=add`. Common shape has to be the same as the shape of two inputs to do addition.
> problem with CombineLayer after ConvLayer

- TFNetworkRecLayer.py
Some changes I made to the ChoiceLayer.
I fixed beam selection for the case of two sources (should have committed this a long time ago...).
I also made changes to support different in- and outgoing beam sizes, which can be useful in case of multiple choice layers.
However, I cannot get different beam sizes to run with the current master, as I run into
`assert latest_beam_size == layer_choice.search_choices.beam_size  # would need fixing...` in `_SubnetworkRecCell._opt_search_resolve()`. The comment seems to indicate you have an idea what needs to be done here, @albertz?
> Choice Layer: beam fix for factored case; allow for different in and out beam sizes

- TFNetworkRecLayer.py
- TFUtil.py
- tests/test_TFNetworkRecLayer.py
- tests/test_TFUtil.py
Changes to support `offset` option in `PositionalEncodingLayer`.
This enables using another layer as offsets to shift positions.
In addition, this removes the previously available option to specify `batch_dim_axis` independently of the input when `add_to_input` is `False`. The output shape is now always set to be the same as the input shape. Please let me know if anyone is against this change.
> PositionalEncodingLayer, changes to support offset

- TFNetworkRecLayer.py
Some recent changes did not reflect sub-layers, in particular those of the ChoiceLayer in case of two targets.
Apart from these minor changes, thanks to correctly backtracking the beams of all output layers of the rec layer via _opt_search_resolve, ChoiceLayer with two targets is finally fully working in the master branch, nice! ':D
> Fixes for ChoiceLayer sub-layers

- TFNetwork.py
- Util.py
If the initial state of the model should be saved, the directory might not yet exist. The code that creates it is called in `log_runtime_info_to_dir`, which only runs during the training.
> Create directory if it doesn't already exist

- TFNetworkRecLayer.py
This is more an issue than a solution.
I get the following error when using two dependent choice layers in the recurrent unit (called 'output_lemma' and 'output_casing', in this order):
```
Exception: get_search_choices src=<ReduceOutLayer 'readout' out_type=Data(shape=(100,), time_dim_axis=None, beam=SearchBeam(name='output/prev:output_casing', beam_size=13), batch_shape_meta=[B,F|100])> base_search_choice=None sources=None.
Search choices cannot be compared.
Layer 1
<_TemplateLayer(ChoiceLayer)(:template:choice) 'output_casing' out_type=Data(shape=(), dtype='int32', sparse=True, dim=5, time_dim_axis=None, beam=SearchBeam(name='output/output_casing', beam_size=13, dependency=SearchBeam(name='output/output_lemma', beam_size=12)), batch_shape_meta=[B]) (construction stack 'output')>
choice …
```
> TemplateLayer: don't normalize to real layer

- EngineBase.py
Sisyphus can only handle existing paths, so .meta has to be part of the path.
> TF model paths are allowed to have .meta postfix

- TFNetworkRecLayer.py
I generalised the implementation of target factors in the ChoiceLayer to an arbitrary number of targets.
Also I changed the tests to 3 instead of 2 targets. A single choice layer with 3 targets works, however the other test, where there are 3 separate ChoiceLayers depending on each other, fails. Something seems to go wrong in `get_search_choices`, I will try to look into this, but help is appreciated.
The two things are only somewhat related, I could also make separate PRs...
> ChoiceLayer: support for more than two targets

- CachedDataset2.py
I think the return value should be of type `str`. It is also mentioned like that in the docstring.
> CachedDataset2, get_data_dtype return as string

- tests/test_TFEngine.py
One more test for `preload_from_files` which covers the typical eval case.
This test fails with 85b3d6aad972b7c592b380cf1b416ebd923f7835 and passes after the fix 083cf37ac75fea98f2a0596c0e2f35f116d40429.
> test_TFEngine, test_init_network_from_config_preload_from_files_eval

- TFNetworkLayer.py
As far as I understand, so far, there is no way to create a non-scalar constant. Taking the shape from the constant if it is an array is the only change necessary to support this.
> ConstantLayer: array constants

- tools/bliss-to-ogg-zip.py
I encountered two issues when using the bliss to ogg zip tool recently.
First, a very small number of the recordings has two channels instead of one (both of them are identical). This results in inconsistent shapes, so I added the possibility to set the number of channels in the ffmpeg calls by using the option `-ac`.
Second, some wav file could not be read by ffmpeg. The suggestions from [here](https://stackoverflow.com/questions/17809407/ffmpeg-cannot-open-a-simple-microsoft-wav-file-exported-with-audacity) and [here](https://trac.ffmpeg.org/ticket/2810), forcing the audio codec using `$ ffmpeg -acodec pcm_s16le ...`, solved my problem so I added the option to do that in the bliss to ogg zip tool.
> Fixes in bliss to ogg zip tool

- .gitmodules
- extern/HawkAaronWarpTransducer/__init__.py
- tests/test_TFNativeOp.py
Hi,
This PR implements the wrapper around [warp-transducer](https://github.com/HawkAaron/warp-transducer).
The loss can then be used like this:
`from extern.warprnnt import rnnt_loss`
with the definition `rnnt_loss(acts, labels, input_lengths, label_lengths, blank_label=0)`, defined in `extern/warprnnt/__init__.py`
> WarpRNNT wrapper

- TFNetworkLayer.py
Reuse layer name scope when using `batch_norm` option to avoid errors e.g. for `RecLayer`.
> TFNetworkLayer: fix name scope for batch_norm opt

- TFNetworkRecLayer.py
Currently the search score depends on the batch and beam size when doing length normalization. This is because the implementation of length normalization in ChoiceLayer introduces a factor of maximum decoding length for all scores, which can vary depending on which sequences are in the batch/beam.
This PR removes the factor, such that ChoiceLayer returns the expected score/seq_lens once search is done.
> ChoiceLayer: return length normalized score as expected

- TFUtil.py
Modified `get_initializer()` in `TFUtil.py` such that it is possible to directly pass a numpy array for initialization, e.g. using `{'class': 'conv',..., 'forward_weights_init': np.array([1, 2, 3])}`. The shape of the array has to be compatible with the shape of the initialized tensor.
> Allow passing np array directly for init

- Dataset.py
As discussed in #294, I think the function bodies can be removed/replaced by a NotImplementedException
I ran the dataset tests locally, but made a PR to make sure all tests are fine.
> removed unused get_seq_length/get_seq_length_nd bodies

- tools/bliss-to-ogg-zip.py
I switched recently from my own custom tool for ogg zip creation to the official one, and found that it crashes when I have non-ASCII characters in the "orth" segments. I could fix the problem by adding a custom parser that runs with UTF-8 encoding. I am just not sure if this creates any unwanted side-effects.
> UTF-8 compatibility for bliss-to-ogg-zip tool

- TFNetworkLayer.py
- tests/test_TFNetworkLayer.py
The MergeDimsLayer did not consider any static axes when updating the size placeholder. So if e.g. a dynamic time axis was merged with a fixed sized spatial axis, the resulting dynamic axis would be equal to the original time axis, and not be multiplied.
> fixed size_placeholder bug in MergeDimsLayer, added test case

- TFCompat.py
Shouldn't this check against v2? So that v2 is none if it does not exist? Because my current TF1.13 versions are now crashing with:
```
File "/work/asr4/rossenbach/sisyphus_work_folders/librispeech_tts_work/returnn/helpers/rossenbach/checkout/CheckoutRETURNN.xxswwSAwc3ZC/output/crnn/5aabe210ca167ee83ff38786a109406a63e8a6bb/TFCompat.py", line 22, in <module>
line: v2 = tf.compat.v2
locals:
v2 = <not found>
tf = <local> <module 'tensorflow' from '/work/asr4/rossenbach/env/python37_tf_1.13/lib/python3.7/site-packages/tensorflow/__init__.py'>
tf.compat = <local> <module 'tensorflow._api.v1.compat' from '/work/asr4/rossenbach/env/python37_tf_1.13/lib/python3.7/site-packages/tensorflow/_api/v1/compat/__init__.py'>
tf.compat.v2 = <local> !AttributeError: module 'tensorflow._api.v1.compat' has no …
```
> fix in TFCompat

- GeneratingDataset.py
For debugging purposes I needed a `DummyDataset`, which provides more than just the `"data"` and `"classes"` data key (cf. Issue https://github.com/rwth-i6/returnn/issues/305). So, I extended the `DummyDataset` class with a `DummyDatasetMultipleDataKeys` class, which enables the user to define multiple data points.
> ADDED: DummyDatasetMultipleDataKeys to GeneratingDataset.py

- TFNetworkLayer.py
- tests/test_TFNetworkLayer.py
I added `get_out_data_from_opts()` for the `ActivationLayer` and added the case of the abs activation on complex values, in which case the output `dtype` should change from `complex64` to `float32`.
> ActivationLayer output dtype

- TFNetworkLayer.py
- TFNetworkRecLayer.py
- TFUtil.py
- Util.py
- tests/test_TFEngine.py
This PR adds an additional test case to enable the construction of specific attention methods that do not require an explicit encoder context. This added test case uses an explicit DimensionTag for correct template construction and an `initial_output` for the weight-feedback based on the encoder for correct tensor shapes.
Two fixes were needed for this to run:
- the deepcopy function does not try to copy tensors and dimension tags
- the `declare_same_as` function to adopt to external DimensionTags is now aware of a possible beam search and adjusts the batch axis accordingly
> Support for attention energies without encoder dependencies

- Dataset.py
- HDFDataset.py
- LmDataset.py
- MetaDataset.py
Let's follow up on the discussion in 761062b. This commit removed support for the sorting options available via `Dataset.get_seq_order_for_epoch()` in CombinedDataset.
I just boldly put our code here, but it's secondary. Let's discuss the principles first :)
What I want to achieve is to combine several datasets such that they behave exactly as if a dataset would have been created from the merged input files. Our use case is that we already have TranslationDatasets setups (possibly dumped to HDF) on disk for several language pairs and now want to train a multilingual system using those datasets without creating new merged corpora for each new language pair combination. Our bilingual systems use "laplace" sequence ordering and we want to keep that for multilingual systems.
For this, …
> CombinedDataset: recovery of general sorting support

- TFUtil.py
I added another case in `get_initializer()` that allows passing strings which result in a numpy array when passed to `eval()`. Example for a possible usage: `'forward_weights_init': 'numpy.hanning(400).reshape((400, 1, 1, 1))'`
> TFUtil: np array initialization

- returnn/datasets/basic.py
- returnn/datasets/cached.py
- returnn/datasets/cached2.py
- returnn/datasets/generating.py
- returnn/datasets/hdf.py
- returnn/datasets/lm.py
- returnn/datasets/meta.py
- returnn/datasets/numpy_dump.py
- returnn/datasets/raw_wav.py
- returnn/datasets/sprint.py
- returnn/datasets/stereo.py
I introduced a parameter to init_seq_order by which you can set a predefined sequence order via indices, rather than using sequence tags, and used this in CombinedDataset to set the sequence orderings of the subsets.
It's not super nice to have two different ways to do the same thing, but we need this for efficiency. I tested this with a CombinedDataset having three HDFDatasets as subsets with 1M sequences each. With the current implementation, which loads all tags of the subsets and then passes the right tags to the subsets dataset, dataset initialization takes 18 minutes. With this change it reduces to 30 seconds. Also, memory consumption reduces by 500MB, which if you scale it to 10M or 100M sequences becomes significant.
95% of the changes are just adjusting all init_seq_order calls. …
> CombinedDataset: sequence ordering of subsets via indices

- returnn/datasets/generating.py
- returnn/util/basic.py
This fixes #346 but it is valid only if we want to keep int/float32 all over the code as it is now.
> Converted data of Task12AXDataset to single precision

- docs/configuration_reference/model_loading.rst
It seems that the file EngineBase.py doesn't exist anymore. I changed the link to make it point to the file containing the class EngineBase.
> Fixes broken link in Model Loading doc page

- returnn/__main__.py
- returnn/tf/native_op.py
- returnn/tf/util/basic.py
- returnn/util/basic.py
I want to use RETURNN in a pipeable script (with log-verbosity:1), and right now these messages might get in my `stdout`. I am not sure how to find other messages that can still appear.
I assumed `stderr` is fine, because I did not want to add an additional dependency on `Log`.
> move non-log stdout print messages to log.v3 

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
This allows to pass a name of a layer as `postfix` of the `postfix_in_time`-Layer.
Currently, this requires the postfix-Layer to not have a time dimension itself. However to implement that, it might be nicer to reuse the code from `PrefixInTimeLayer`. Maybe then it's nicer to add a `ConcatInTime`-Layer that concats all `from`-Arguments or something like that.
Also, this PR adds a test case for `PrevTimeLayer` that also tests its old behaviour.
> PostfixInTime: Allow postfix to be another layer

- returnn/tf/util/basic.py
- returnn/util/sig_proc.py
I added a `GammatoneFilterbankInitializer` class that can be used to initialize a convolutional layer with the parameters of a gammatone filterbank.
Main references are the paper 
>Schlueter, Ralf, et al. "Gammatone features and feature combination for large vocabulary speech recognition." ICASSP 2007
and the RASR code as indicated in the comments.
> tf util: add GammatoneFilterbankInitializer

- tests/test_TFNetworkRecLayer.py
Previously, this test case failed, see #285.
Now, it seems to pass.
Also, I changed this to work with TF 2.3, and now test both permutations of the `cum_att_energy` input layers.
> Test case for cumulated attention weights during search

- returnn/tf/layers/rec.py
When inside a recurrent loop, store a single `prev_k` and `prev_v` instead of a concatenation `prev_kv`. This saves a split-operation of the `prev_kv`-tensor with length (t-1) at time step t into seperate `prev_k` and `prev_v`, which in total had quadratic memory consumption in t. We still have quadratic memory usage even with this change, but it is much better than before.
As a reference: I managed to reduce the peak memory (measured by tfprof) of a 6 Layer Trafo for MT with mostly recurrent decoder layers (besides embeddings) with Batch Size 2350 from around 9000 MB to 6800 MB.
This is still not ideal, as both the in-loop version could have the same memory footprint as the optimized one, however that would be a major change to implement (the fully parallel model only requires 4800 MB). …
> SelfAttention: Reduce memory footprint when in loop

- returnn/tf/layers/basic.py
When doing a transposed convolution with strides, the output shape is not configured correctly (note that by default, strides are set to filter size). 
The proposed change adapts the shape of the non-dynamic spatial axes according to the stride. Note that this is only valid for `padding="SAME"`, which is always used here because it is the default in `tf.nn.conv2d_transpose`.
> TransposedConvLayer: fix output shape

- returnn/tf/layers/basic.py
Vocabulary has to be set to None, otherwise we run into a dimension mismatch assertion (2 vs. voc size). 
This was unintentionally dropped in 4578b43, I assume.
@mattiadg Take a quick look.
> CompareLayer: output cannot have voc

- returnn/datasets/meta.py
This is something I overlooked when we decided to use `_expand_dataset_sec_idxs()` for both known and unknown num_seqs. `self.used_num_seqs_per_subset` in the case of known num_seqs is not just the total number of sequences in the subsets, but we have to account for sequence ordering, sampling, etc.
This lead to running into the exception at the bottom of `_expand_dataset_sec_idxs()` at the end of an epoch, however only in case we artificially increase the number of sequences, e.g. by repeat_epoch or sampling more sequences than the total number.
> CombinedDataset: fix crash at end of epoch if sampling_size > num_seq

- returnn/tf/network.py
When browsing through the `TFNetwork` code, I found that there two functions are called at no position in the code. I also did a complete search for the function names, which led to no results.
> tf.network: remove dead code

- returnn/__main__.py
- returnn/tf/engine.py
- returnn/tf/layers/base.py
- returnn/tf/network.py
- tests/test_TFEngine.py
- Adds a DataNotAvailable Exception
- Aborts construction stack when the output is flagged
as available_for_inference=False
This is related to issue #372, and approaches the problem by introducing an Exception that is caught when calling the network construction from "register_as_extern_data". In all other cases the Exception will be raised globally.
> tf.network: check for data availabibility

- .gitmodules
- returnn/extern/WarpRna/__init__.py
- tests/test_TFNativeOp.py
Hi,
because my custom TF code for the RNA loss implementation is too slow for training,
I wrote a Tensorflow binding to the [warp-rna](https://github.com/1ytic/warp-rna) code (which is for PyTorch).
The binding itself is in my [fork](https://github.com/Spotlight0xff/warp-rna).
Other than that, this is fairly standard and very similar to the `HawkAaronWarpTransducer`.
Cheers, André
> Warp-RNA TF wrapper

- returnn/tf/native_op.py
These preprocessor macros are tagged as being redefined by the C++ compiler.
> Handle more symbol redefinitions in generated kernels

- returnn/tf/engine.py
I got
```
File "/home/pwilken/src/returnn_dev/returnn/tf/engine.py", line 1961, in check_uninitialized_vars
line: var_mask = tf.logical_not(tf.stack(
[tf_compat.v1.is_variable_initialized(v) for v in var_list])).eval(session=self.tf_session)
[...]
ValueError: Cannot use the given session to evaluate tensor: the tensor's graph is different from the session's graph.
```
when running two RETURNN Engines in the same python session (which works fine except for this issue!).
What I do is:
1. Create `engine_1 = Engine(...)` and run `engine_1.init_network_from_config()`
2. Create `engine_2 = Engine(...)` and run `engine_2.init_network_from_config()`
3. Running `engine_1.search_single_string_to_string_seq(...)` resulting in the error
(1. and 2. are part of a server startup, so I can't run 3. …
> Fixed confusion of TF graphs when running multiple Engines

- returnn/tf/layers/basic.py
Changes the behaviour of `get_out_data_from_opts` in `ReduceLayer` for `mode=""` to fix issue with the `SqueezeLayer` and sparse data input
Fixes #388
> fix sparse intput for SqueezeLayer

- returnn/tf/layers/basic.py
When the sources of a DotLayer have different batch dim axes, the key
in the size_placeholder has to inferred according to the new batch dim
of the DotLayer, and not the source layer this axis was originally from.
> DotLayer: Fix size_placeholder bug

- tests/test_TFNetworkRecLayer.py
A test case for the issue I had previously, which I fixed in #395.
> Add test case for accessing SplitLayer outputs in RecLayer

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
This `RepeatLayer` extends `tf.repeat` to work with independent repetitions along the batch axis. It should in theory work on any axis, but I only wrote test cases for BTF, TBF, and BFT so far, as those are the most likely application cases.
> Repeat layer

- returnn/tf/util/basic.py
I'd like to add the GELU activation to https://github.com/rwth-i6/pytorch-to-returnn. We could simply do that by adding the existing RETURNN GELU analogous to e.g. ReLU. However, the implementation in PyTorch differs, see e.g.
https://discuss.pytorch.org/t/gelu-pytorch-formula/79875/2
https://github.com/pytorch/pytorch/blob/b7f4b6a6de30116f1b44a08fab9499dd5eb2de7d/test/cpp/api/functional.cpp#L839-L845
Therefore, I added `gelu3` which now imitates the PyTorch GELU. The name is of course debatable. I chose it because the alternative `gelu2` is already there, but am open to other suggestions.
> Add PyTorch-like GELU

- returnn/tf/util/basic.py
Small fix to allow using `ActivationLayer` with `activation="log"` in tf2 as well.
> fix log activation for tf2

- returnn/tf/layers/rec.py
- tests/test_TFEngine.py
- tests/test_TFNetworkRecLayer.py
This is the issue I discovered in #395.
The test passes if one reverts 8f16741. But the TODO suggests that this should be handled in `_move_outside_loop()` instead, I will try.
> Failing test for case where sub-layer is optimized out

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
Add `RandIntLayer` which accepts a shape based on `DimensionTag`s or ints (only for static dims) and creates random ints using `tf.random.uniform`.
> add RandIntLayer

- returnn/tf/layers/basic.py
Before, there was some extra logic in `CompareLayer` ensuring the `batch_dim_axis` of all input tensors align. That logic failed if one input does not have a `batch_dim_axis`.
I removed this extra handling of the `batch_dim_axis` entirely, because I think `Data.get_common_data` should handle it correctly. Or is there a reason to have this?
> CompareLayer: Support inputs without batch dim

- returnn/tf/layers/basic.py
- returnn/tf/util/data.py
- tests/test_TFNetworkLayer.py
This is especially useful to use `SwitchLayer` as a generic masking
layer. If you have some sort of `"mask"` for some `"input"` layer,
use `condition="mask", true_from="input", false_from=float("-inf")`
to e.g. mask out all unmasked values with -inf.
This commit also moves the logic from `ConstantLayer.get_out_data_from_opts` to `Data.template_from_constant` as it is very reusable. Sorry, that's a bit messy.
> SwitchLayer: Constant `true_from`/`false_from` params

- returnn/datasets/hdf.py
- returnn/datasets/meta.py
I thought fixing `hdf_dump` to dump some of my datasets was simpler, but as there were now some additional problems to be solved a PR seems to be the safer option.
So `hdf_dump` did not allow for Datasets having no targets (but only data), and I did not work with MetaDatasets at all, as the child datasets did not get a `init_seq_order` call passed.
> fix hdf_dump without target, MetaDataset workaround

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
This was the expected behavior from most users,
after a discussion whether [B,T,F|5] merge "except_batch"
should result in [B,T|F] or [B,F] or [B,T].
> MergeDimsLayer, unset time-dim if it got merged

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
See the test case I added, [which currently fails](https://github.com/rwth-i6/returnn/runs/1875491241?check_suite_focus=true).
I get the error:
```
File "/u/petrick/software/returnn/official/returnn/tf/network.py", line 708, in _create_layer
line: assert output_template_special_axes == output_special_axes, "%s %r: not equal: %r == %r, from data %r -> %r" % (
layer_class.__name__, name,
output_template_special_axes, output_special_axes,
output_template, layer.output)
locals:
output_template_special_axes = <local> {'time_dim_axis': 1, 'feature_dim_axis': 2}
output_special_axes = <local> {'time_dim_axis': 1, 'feature_dim_axis': 3}
layer_class = <local> <class 'returnn.tf.layers.basic.SplitLayer'>
layer_class.__name__ = <local> 'SplitLayer', len = 10
name = <local> 'split_qkv', len = 9 …
```
> SplitLayer template construction fails if used after SplitDimsLayer

- returnn/tf/layers/basic.py
- returnn/tf/util/data.py
Adds some basic checks about `size_placeholder` in `Data.sanity_check`.
E.g. in `MergeDimsLayer`, this was set incorrectly in `get_out_data_from_opts`, but only in `__init__` (because it needs to create a new size tensor).
I now changed it so that at least the axes are correct.
> Check size_placeholder in Data.sanity_check

- returnn/datasets/cached.py
- returnn/datasets/hdf.py
Necessary changes to support HDF files without 'inputs'.
Also, there was a check that targets have to be of equal sequence length in the HDFDatasetWriter. I tested targets with different lengths and I didn't find a reason why this check was there.
> HDFDataset / HDFDatasetWriter: Support for only using targets

- returnn/tf/layers/basic.py
- returnn/tf/util/data.py
`res.batch_shape[res.batch_dim_axis]` will always be `None`,
therefore the existing check did not work if we wanted to
unbroadcast an added batch dimension.
> Data.copy_add_dim_tag: Fix unbroadcast batch dim

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
`SwitchLayer` previously just copied its `dim` from `true_data`. If (e.g.) `true_data` is a constant scalar, but `false_data` has a `feature_dim_axis`, then also the output will have a `feature_dim_axis`, and thus this is wrong.
> SwitchLayer: Set dim correctly

- returnn/datasets/hdf.py
Needed when only having dense targets. In this case, although `self.labels` is unset we don't intend to use the deprecated(?) `fin["labels"]`.
> HDFDataset: support having no target labels

- returnn/tf/layers/basic.py
- returnn/tf/layers/rec.py
The problem was that in template construction we re-initialize some "partially_finished" layers in the end and the sub-layers were not included here. Only after re-initialization the beam is set.
The test still fails because the `base:encoder` has a different time-dim which is kept in the loop, but this is a separate issue and can be fixed by using `"from": "encoder"` in the rec layer and then `"data:source"` in `"output_prob"`. (Or by using this "same dim tag" in extern_data I guess)
> Fixes for #450

- returnn/datasets/basic.py
Targets and references may not have a time dimension and thus the data passed to `serialize_data` can be 0D.
> Fix serialization in dataset of data without time dimension

- returnn/datasets/generating.py
- returnn/datasets/lm.py
- tools/bliss-collect-seq-lens.py
- tools/bliss-get-segment-names.py
- tools/bliss-to-ogg-zip.py
- tools/collect-orth-symbols.py
- tools/collect-words.py
- tools/extract_state_tying_from_dataset.py
`Element.text` is None if the node has no text content (happened in my case for silence segments).
> Support empty orth in bliss files

- returnn/tf/data_pipeline.py
- returnn/tf/layers/base.py
- returnn/tf/network.py
- returnn/tf/util/data.py
- tools/compile_tf_graph.py
> Direct support for flattened/packed arrays

- returnn/tf/layers/basic.py
Somehow forgot the softmax in #460 
The output may not have a time dimension and seq_lens and thus _flatten_or_merge fails if output_flat is None.
This is already handled in init so we don't have to do this case distinction here again.
> Use output_before_softmax_flat in get_output_target_scores

- docs/configuration_reference/model_loading.rst
- returnn/tf/network.py
If this is set to true, the variables not found in the current checkpoint will be ignored during loading and then (randomly) initialized by TF.
In my case I trained a model, and then wanted to do search with another network dict which included a random initialized, non-trainable variable.
> Add init_missing_vars

- returnn/util/py-to-pickle.cpp
- tests/test_Util.py
Currently, py-to-pickle crashes results in a parse error when the py object contains None.
I needed support for this since some of my oggzip files contained None s (speaker information).
> Adds support for None in py-to-pickle.cpp

- returnn/tf/layers/base.py
- returnn/tf/layers/basic.py
- returnn/tf/layers/rec.py
- returnn/tf/network.py
- tests/test_TFNetworkLayer.py
- tests/test_TFNetworkRecLayer.py
Now the dependencies on layers of subnetworks (via `SubnetworkLayer`) are handled more explicitly. This enables `RecLayer` to optimize layers individually, even from subnetworks.
See `test_reclayer_subnetwork_sublayer` as an example.
This is a quite heavy change. But mostly only because it was quite complicated before, and now it simplifies many things, but some other parts also become more complex. So it shifted the complexity. I hope that it is overall more reliable now.
I hope that when all tests are passing, we can be quite sure that this does not break anything. But better check through to be sure.
> New subnetwork sublayer construction logic

- tools/dump-dataset.py
`eval` and `dev` are set to `None` at the end of `init(config_str, config_dataset, verbosity)` so using `config:dev` or `config:eval` caused an error. 
Using `config.typed_value("dev",None)` instead, works fine.
> Error for --dataset eval & dev

- returnn/tf/util/data.py
I added the format `stag-single:<idx>:<name>` for dim tags to be able to distinguish spatial axes in pytorch-to-returnn. `idx` is relative to the matching stags, i.e., it is the index among the list of spatial dims matching `name`.
> Data: add dim tag format stag-single:<idx>:<name>

- returnn/tf/layers/rec.py
Normalize by length^alpha instead of length to be able to tune the length of the generated sequences. I thought this is quite common in practice (including alpha as the variable name), however I could only find a reference to a more complicated formula here: https://arxiv.org/pdf/1609.08144.pdf equation 14.
I needed this to tune the length of translations of partial sentences ("chunks") that we use for simultaneous MT.
> ChoiceLayer: added alpha for length normalization

- returnn/tf/util/basic.py
If `get_name_scope_of_tensor(x)` returns empty string, the resulting `name_scope` was invalid because of the leading `/`. This happened to me when using `compile_tf_graph.py`. I can check again for which tensor this happened if important.
> reuse_name_scope_of_tensor: fix invalid name if no scope

- returnn/tf/layers/base.py
- returnn/tf/layers/basic.py
- returnn/tf/network.py
1. Fixed one place where trying to access the size placeholder fails in `get_out_data_from_opts()` when the input is a `DataNotAvailableLayer`. I suspect there might be more such cases in the code.
2. `DataNotAvailableLayer` has to do "register_as_extern_data" because the data template might be needed at inference time, e.g. as the target of a ChoiceLayer. Usually this happens in `LayerBase.post_init()`, however this is not called for `DataNotAvailableLayer`.
> DataNotAvailableLayer fixes

- docs/user_guide/recurrent_subnet.rst
Added a small paragraph as documentation how to access the index of the current time step within a recurrent unit.
> Documentation for accessing time step index

- returnn/tf/network.py
When saving the variables of a `ZoneoutLstm` layer in a checkpoint an extra "rnn" is added in the name of the variables. This breaks the process of loading the parameters from a checkpoint.
``` log
Variables to restore which are not in checkpoint:
output/rec/slow_rnn/masked/lstm0/rec/lstm_cell/bias
output/rec/slow_rnn/masked/lstm0/rec/lstm_cell/kernel
Variables in checkpoint which are not needed for restore:
output/rec/slow_rnn/masked/lstm0/rec/rnn/lstm_cell/bias
output/rec/slow_rnn/masked/lstm0/rec/rnn/lstm_cell/kernel
```
It happens [here](https://github.com/rwth-i6/returnn/blob/522ce85122103fc8a21df5798e9596476250a96d/returnn/tf/layers/rec.py#L701) when calling the [tensorflow.python.ops.rnn.dynamic_rnn()](https://github.com/tensorflow/tensorflow/blob/6bba1b6e6d0a3d57258acd204987869806b …
> Solve extra added rnn scope

- returnn/tf/layers/basic.py
If we want to reinterpret `data:classes` with `ReinterpretDataLayer` and change the `sparse_dim`, via either `set_sparse_dim` or `increase_sparse_dim`, the output data ends up in a mismatch with the vocab dimension.
Here I solve this by **removing the vocab**.
But one could think of a more generic way of doing this.
In most of the cases, we need to do this when when we either add an extra label(e.g. EOS or blank) or want to remove it.
I am not sure if it's possible to change the vocab so easily?
> ReinterpretDataLayer: remove vocab if dim changes

- returnn/tf/layers/basic.py
I assume it was intended this way as the default value for `remove_padding` is 0 and later `len(remove_padding)` is checked, which crashes with the default value right now.
> small fix in TransposedConvLayer

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
This PR copies the parameters used for `batch_norm()` in the `LayerBase` directly into the `BatchNorm` layer, instead of them being extracted from the `kwargs` in the `BatchNorm` layer. This change should not make functional differences and is in order to make the generated `BatchNorm` layer in the `returnn_common` interfaces easier to use. This change enables directly defining the parameters of the layer in the new interface instead of handing over a dict of strings.
> Explicit definition of the batch norm parameters in the BatchNorm Layer

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
When using the Activation Layer with absolute activation for the output of a stft layer there is an assertion failure that the output should have type "float32" but actually has type "complex64". I propose a fix of the problem and a test for its correctness.
> small fix for activation layer to work with stft layer using absolute activation

- returnn/tf/layers/base.py
- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
At least I assume they are unused.
Likely a user would not provide a tf.Tensor in a config.
Or the specified type was wrong
and this was supposed to be a float.
Anyway, I still don't see
how this would have been used potentially.
Maybe this was a relict from the Theano code conversion.
> batch norm, cleanup unused args

- tools/compile_tf_graph.py
In many of my setups, I use `compile_tf_graph.py` to compile the graph based on my RETURNN config and then use this graph in RASR for recognition. In RASR, I always used `output/output_batch_major` as tensor name to obtain the posteriors that I needed.
This does not work as expected anymore, since `network.layers` used to include only `SubnetworkLayers` but now also includes all layers inside the subnetwork. Therefore, if I have a subnetwork with a layer named "output" inside, the name of the tensor I actually want changes to `output/output_batch_major_1`.
We can avoid this by using absolute layer names in the script. Not sure if this breaks some setups people recently built, but obviously not doing this also breaks setups as in my case.
> compile_tf_graph: use absolute layer names

- returnn/tf/util/basic.py
When adding a param, most layers pass sth like `self.network.random.randint(2 ** 31)` as seed to `get_initializer`: e.g.
https://github.com/rwth-i6/returnn/blob/master/returnn/tf/layers/basic.py#L6911
However, when the provided initializer already contains a seed, this is just overridden: E.g. 
```
{'class': 'variable', 'add_batch_axis': True, 'shape': (8, 1, 64, 2), 'trainable': False,
'init': "variance_scaling_initializer(mode='fan_in', distribution='uniform', 'scale=1.0, seed=100)'}
```
will be initialized differently for different global `random_seed`s.
That is definitely not what I expect: If I explicitly provide a seed to the initializer, I expect it to always initialize my tensor to the same value - independent of the network seed.
In this PR, I change `get_initializer` to only …
> get_initializer: Do not override seed set by user

- returnn/util/basic.py
To create search output files in the py format we currently kind of rely on `better_repr` to generate valid python code.
But this is not the case if the output contains infs or nans (e.g. beam scores (can happen in my case since I am doing a kind of constrained search where I mask invalid hypotheses)).
To fix this, this changes the output of `better_repr` from e.g. `-inf` to `float('-inf')`.
> Handle nan and inf in better_repr

- returnn/tf/layers/base.py
A student worker at AppTek found that using batch norm during search has a lot of computational overhead (up tp 30%), and the graph includes nodes that should not be needed during search, as e.g. re-estimating the variance and mean.
This PR fixes this issue, reducing the computational share of the BN from 30% to 13% in this specific case. The problem is that TF does not detect multiplications with 0 automatically, and will still run the full graph, thus, zero cases need to be handled explicitely. 
The adding the epsilon also had a share of 2% computation, so I also disabled the addition when the epsilon is zero.
> Fix unused TF operations in Batchnorm

- returnn/tf/layers/basic.py
I had `extra` inputs of a HDF dump layer which did not have any batch dim.
Here I change it so that all `extra` inputs without batch dim get an unbroadcasted batch dim of the main input.
> HDFDumpLayer: Add batch dim to "extra" inputs

- docs/generate_optimizer.py
- returnn/tf/updater.py
- tests/test_TFEngine.py
Some bugfixing and extending features in the `updater.py` code:
- Keras optimizers are now longer stored as wrapper function reference (caused problems due to inconsistencies of `type` vs `callable`)
- Optimizer types can directly be used as "class" parameter -> allows to use external optimizers such as those from `tensorflow_addons` 
- The documentation correctly displays also the Optimizers available via Keras (e.g. Nadam and Adamax)
> Fix optimizer selection code

- returnn/tf/layers/base.py
- returnn/tf/layers/basic.py
- returnn/tf/layers/rec.py
- returnn/tf/layers/signal_processing.py
- returnn/tf/network.py
- returnn/tf/util/basic.py
- returnn/tf/util/data.py
Follow-up from #577. Needed for #391.
This introduces the `dim_tags` argument and attribute for `Data`.
This disallows `Data.shape` and `Data.batch_dim_axis` assignments.
Much `Data` util code got adapted to consistently make use of dim tags.
Many layers got adapted to not operate on the shape but on dim tags instead.
> Explicit Data dimension tags

- .gitignore
- returnn/tf/layers/base.py
- returnn/tf/layers/rec.py
- returnn/tf/network.py
- returnn/tf/util/data.py
> (Random stuff)

- tests/test_TFNetworkRecLayer.py
Moved out from #589.
This was originally a very big PR, which then successively got split up and moved to other PRs (#599 #600 #601 #602 #603 #604 #605 #606 #607 #608 #609 #610 #611 #612 #613 #614 #615 #616 #617 #618 #619 #620 #621 #622 #623 #624), until some remaining small things here (some tests only).
For finding pairs/sets of commits to squash together (and move to separate PRs), I'm using [this script](https://github.com/albertz/helpers/blob/master/git-find-related-commits.py) (explained [here](https://stackoverflow.com/questions/66731069/how-to-find-pairs-groups-of-most-related-commits/66732834#66732834)), which finds pairs of commits which reduce the diff over each commit individually.
Some discussion about how to manage the cleanup is [here …
> (Extend some tests)

- returnn/tf/layers/rec.py
Enable usage of dicts in the `explicit_search_sources` of the choice layer. This is useful when writing custom logic in `custom_score_combine`, that behaves differently, depending on the inputs.
> ChoiceLayer, enable dict in explicit_search_sources

- returnn/tf/layers/basic.py
- returnn/tf/layers/rec.py
- returnn/tf/network.py
- returnn/tf/util/data.py
- tests/test_TFNetworkRecLayer.py
Fixes #569. Also adds test cases.
Needed for #589.
> DotLayer transform maybe var1/var2 when optimized out of loop

- returnn/tf/layers/basic.py
- returnn/tf/util/basic.py
- returnn/tf/util/data.py
- tests/test_TFNetworkLayer.py
- tests/test_TFNetworkRecLayer.py
> DotLayer, mask for dynamic axis

- returnn/tf/layers/base.py
- returnn/tf/layers/rec.py
- returnn/tf/network.py
- returnn/tf/util/basic.py
- returnn/tf/util/data.py
> ControlFlowContext in dim tag, network, Data

- returnn/tf/layers/rec.py
- tests/test_TFNetworkRecLayer.py
> CumConcatLayer

- returnn/tf/layers/rec.py
- tests/test_TFEngine.py
Now that I wanted to continue on fixing the `tf_compile_graph.py` tool, I found out that even my "basic" test case is not working after the recent updates. I wrote a specific engine test case that replicates the error.
The error only appears when no flag (e.g. train or search) is set, otherwise plenty of other tests would fail.
This is the error:
```python3
File "/home/nick/env/tf25/lib/python3.9/site-packages/nose/case.py", line 198, in TestBase.runTest
line: self.test(*self.arg)
locals:
self = <local> test_TFEngine.test_engine_create_network
self.test = <local> <function test_engine_create_network at 0x7f5927e750d0>
self.arg = <local> ()
File "/home/nick/github/returnn/tests/test_TFEngine.py", line 253, in test_engine_create_network
line: engine.create_network(
config=config, …
```
> fixes for uncommon network flags

- .github/workflows/main.yml
- returnn/tf/layers/rec.py
- tests/test_tools.py
- tools/compile_tf_graph.py
Tries to fix issues when compiling with `--rec_step_by_step` by doing the following changes:
- Adapted the code to the new internal structure of the rec layer
- Resolved the dependency issue on the target length for the `cond` state var
- Added two test cases with a simple search decoder, one for default compilation, one for compiling with rec-step-by-step
> Test cases and example fixes for tf_compile_graph with recurrent step

- returnn/tf/data_pipeline.py
- tests/test_TFEngine.py
Was not noticed because the tests that use "single_threaded" create only one batch.
> FeedDictDataProvider: fixed no advance in single threaded case

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
The start argument of SliceNdLayer can now be of any shape and not only of shape (B,) as before. I am not 100% sure if we need any asserts to check for shapes or so. But I think it should work for any non-exotic shapes.
@Zettelkasten #625
> SliceNdLayer now uses GatherLayer to get the slices.

- returnn/datasets/cached.py
- returnn/datasets/hdf.py
@albertz You were right, allowing the `"data"` stream to be provided via a target field in the HDF file is actually useful. And easy to do.
> HDFDataset: support 'data' as target key

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
If we do not do the `set_tag_on_size_tensor`, then the `"_is_size_of_dim_tag"` attribute of the tag will not be set and this can lead to an error in follow-up layers:
```
File "/mnt/projects/i6/returnn/returnn/tf/util/data.py", line 342, in DimensionTag.can_compare
line: assert self.get_tag_from_size_tensor(self.dyn_size).get_same_base() is self
locals:
self = <local> DimensionTag{'sliced-time:segments'[B,'time'[B]]}
self.get_tag_from_size_tensor = <local> <bound method DimensionTag.get_tag_from_size_tensor of <class 'returnn.tf.util.data.DimensionTag'>>
self.dyn_size = <local> <tf.Tensor 'output/rec/segments/Maximum_1:0' shape=(?, ?) dtype=int32>
get_same_base = <not found>
AttributeError: 'NoneType' object has no attribute 'get_same_base'
```
> SliceNdLayer added set_tag_on_size_tensor for dynamic size case

- .github/workflows/main.yml
I get:
```
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/home/runner/.local/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
from tensorflow.python import *
File "/home/runner/.local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 52, in <module>
from tensorflow.core.framework.graph_pb2 import *
File "/home/runner/.local/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
from google.protobuf import descriptor as _descriptor
File "/home/runner/.local/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 113
class DescriptorBase(metaclass=DescriptorMetaclass):
^
SyntaxError: invalid syntax
```
And TF installed this protobuf:
```
Collecting protobuf>=3.3.0
Downloading …
```
> Fix for CI and protobuf on Python 2.7

- returnn/datasets/cached.py
- returnn/datasets/hdf.py
I want to do search on a HDFDataset without having a reference, and without creating a dummy target.
This is possible using `++search_do_eval False`, but I needed these two fixes:
1. Make it possible to provide the target labels in the HDF file without having target data. For this, simply don't include the additional labels in `self.target_keys`. (`self.target_keys` always has to correspond to the existing data, e.g. because of number of `seqLengths` entries)
2. Don't check the missing targets in `check_matched_dataset()` because the dataset might not be able to provide the shape and dtype of missing data. (For HDFDataset, `get_data_dtype()` fails.)
> HDFDataset: search without reference

- returnn/tf/engine.py
- returnn/tf/network.py
For preloading a model where some parameters have been renamed this enables more flexibility than only removing a common prefix.
> allow passing a custom variable name mapping for preloading of parameters

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
Right now, `start` and `size` need to have the same shape when they are given as layers. This suffices for my use cases but we can also add support for different shapes if you think we need them.
> Extend SliceNdLayer to use a layer as the size argument

- returnn/engine/base.py
- returnn/tf/network.py
- returnn/util/basic.py
The allowed checkpoint paths were not consistent across the different parameters, so I tried to clean this up a little bit.
> consistent checkpoint filepattern

- returnn/tf/layers/basic.py
> Extend LengthLayer

- tests/test_TFNetworkRecLayer.py
> Extend test check rec moved out helper

- returnn/tf/util/data.py
For #657.
(The commits maybe should be squashed.)
This partly addresses #672.
> DimensionTag better `same_as` logic (`declare_same_as`), validate graph

- returnn/tf/layers/rec.py
> Rec subset output, fix out dim tag in some cases, declare_same_as

- returnn/tf/layers/rec.py
- returnn/tf/util/data.py
- tests/test_TFNetworkRecLayer.py
Support of accumulation of dynamic sizes (`DimensionTag.dyn_size_ext`) within a recurrent context (`control_flow_context`). E.g. when the dyn size (seq lengths) is of shape [B] inside the loop, and this dyn size changes in every iteration (i.e. `control_flow_context` is set to the rec loop), then the accumulated dyn size outside the loop would have shape [T,B].
Further, when some layer inside the loop has such a dynamic shape [B,T_per_frame], where T_per_frame is the dyn size as mentioned before, this means that we cannot use the current `TensorArray` logic, which expects that elements always have the same shape in every frame. This PR also extends that logic to support that.
This was a request by #635 and also makes sense for #589, #579 (and other related commits for #391).
> Accumulate loop dyn size

- returnn/tf/util/basic.py
Currently, `py_print` always prints to stdout and not to the log file. This change allows to overwrite the output stream, so that the output can be written to the log file (e.g. by `file=log.v5`).
> Allow to overwrite the output stream of py_print

- tests/test_TFNetworkRecLayer.py
Some tests for #391.
I didn't run any of this yet (so most likely buggy) because there is no implementation.
It still needs `CumConcatLayer` from #589, but also the `common` arguments for `DotLayer` from #569.
Also, some way to set dim tags (e.g. `set_dim_tags: Dict[str, DimensionTag]` for `ReinterpretDataLayer`. I'm not sure, didn't we add this already somewhere?)
We might also want more tests than this: e.g. some with positional encoding.
> Tests for self attention using CumConcatLayer

- returnn/tf/layers/basic.py
The current `activation` parameter is not necessary and leads to a confusing constructor signature when using the new returnn_common modules.
> SoftmaxLayer fix constructor signature

- returnn/config.py
Overwriting a config param "++param" with a function tag from the current config (e.g.: `++search_data "config:get_sprint_dataset('dev')"` ) fails if the param was already set in the config, and had a different type.
Adding a warning; so user knows that the evaluation failed because the param was previously set in the config.
Also if the evaluation fails, it will use the param as-is. ( Optional )
> added warning when extra config parameter can't be evaluated

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
Fix #704.
WARNING: This potentially changed the behavior of configs.
E.g. the one reported in #703.
Most of the attention and transducer encoders which used initial convolutional layers.
Related is #596. Maybe actually the fix for that in #683 introduces this new bug.
> SplitDimsLayer fix feature_dim_axis on feature-dim split

- returnn/tf/layers/rec.py
Failed for me when it is a template layer (e.g. "prev:xy").
> Rec initial state via layer, extra check

- returnn/tf/layers/basic.py
- returnn/tf/util/basic.py
- returnn/tf/util/data.py
- tests/test_TFNetworkLayer.py
This PR adds `UnflattenBatchLayer` which is the inverse of the `FlattenBatchLayer`. It should undo the flattening and restore the original data in batch major/time major format as it was input to the `FlattenBatchLayer`.
> Add UnflattenBatchLayer

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
Fix #763.
As this should not have any influence on behavior, this does not need a new behavior version.
> VariableLayer, change default add_batch_axis to False

- returnn/tf/layers/base.py
- returnn/tf/layers/basic.py
- returnn/tf/network.py
- returnn/tf/util/data.py
#597
`in_dim` is checked for many common cases for verification in `LayerBase` (just that the dim exists in the input, if there is a single input).
`in_dim` is also used in _ConcatInputLayer to define the concatenated feature dim.
`out_dim` is further used for verification in `LayerBase` (just that the dim exists in the output).
`out_dim` is used for layers which rely on `_base_get_out_data_from_opts`, e.g. `LinearLayer`, to define the output feature dim.
`out_dim` is used by `CopyLayer` to define a potential new concatenated output feature dim.
> Generic LayerBase in_dim and out_dim options

- returnn/tf/layers/basic.py
#597
Also fix #570.
`out_spatial_dim` should be consistent to what we use for `ConvLayer` and `PoolLayer`.
This is only relevant with `padding=="valid"` or `stride!=1`.
> WindowLayer, window_dim and out_spatial_dim

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
There was a bug in the repeat layer which we only detected at generation time. If there were non-zero values in the padded area of the repetition input, the output would be wrong. Unfortunately the original test case did not cover this.
> fix masking for repeat layer

- returnn/tf/layers/base.py
- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
> test_LinearLayer_in_dim_spatial, allow in_dim not feature dim

- docs/configuration_reference/behavior_version.rst
- returnn/tf/layers/basic.py
- returnn/tf/layers/rec.py
- returnn/tf/util/data.py
- returnn/util/basic.py
- tests/test_TFEngine.py
- tests/test_TFNetworkLayer.py
- tests/test_TFNetworkRecLayer.py
Fix #654.
Also introduce `Data.get_axes_from_description` `"dim:%i"` variant. This is mostly as a simple way to fix many of the test cases. But I guess it could also be useful for the user in general. At least as a simple intermediate solution, once people start using dim tags (#597).
> MergeDimsLayer, only allow keep_order=True

- returnn/tf/layers/basic.py
- returnn/tf/util/data.py
- tests/test_TFNetworkRecLayer.py
#597
Fix 2D/3D convolution/pooling (`ConvLayer`/`PoolLayer`) depends on order of axes (#594), when `in_spatial_dims` is used. There should be a follow-up maybe where this is required (for 2D/3D), with new behavior version.
Fix handling of unrelated dims, and also rec automatic optimization (#573).
> ConvLayer and PoolLayer, in_dim, in_spatial_dims, out_dim, out_spatial_dims

- returnn/tf/layers/rec.py
> MaskedComputationLayer, out_spatial_dim option

- returnn/tf/layers/basic.py
The `fast_bw` layer has this, but the loss not. This PR makes this consistent.
> add tdp scale for fast_bw loss

- returnn/tf/layers/rec.py
- returnn/tf/util/data.py
- tests/test_TFNetworkRecLayer.py
Similar to #789.
Fix `RecLayer` for #573.
> RecLayer support unrelated dims

- returnn/tf/layers/basic.py
> ConcatLayer, add out_dim

- returnn/tf/util/data.py
I have a case in the PyTorch-to-RETURNN converter, where `Data.get_axes_by_tag_name` runs into a problem when checking `tag.description.lower()` because the `DimensionTag` that is created in `Data.copy_template_unpack_batch` does not have a `description`. This fixes the error for me, but I'm not sure if it should be fixed in a more generic way since creating a `DimensionTag` with `description=None` is allowed in general and could maybe lead to this error in other cases as well.
> fix for Data.copy_template_unpack_batch

- returnn/util/basic.py
https://github.com/tensorflow/tensorflow/commit/f09d3e299752226f7a28c09a
https://github.com/tensorflow/tensorflow/issues/53313
https://github.com/tensorflow/tensorflow/blob/908e8010ff2c/.bazelrc#L320
The C++14 option is supported since a long time in most compilers,
and this is backward compatible,
so there shouldn't really be any issues.
> Update to C++14 (needed for TensorFlow 2.7)

- returnn/tf/layers/base.py
- tests/test_TFNetworkLayer.py
Currently, the shape of output_flat is set to the original data shape (that does not include the batch dim), i.e. the length of the new batch x time dim is set to the length of the time dim (even if it is static).
> Fixes the shape of output_flat in loss with a static time dimension

- returnn/tf/layers/basic.py
> DotLayer, single reduce argument

- returnn/tf/layers/basic.py
> GatingLayer, handle out_dim

- returnn/tf/layers/basic.py
> NormLayer, axis option

- returnn/tf/layers/base.py
- returnn/tf/util/data.py
- tests/test_TFNetworkLayer.py
Some alternative to #586 which is purely on dim tag level.
When used via `get_axis_from_description`, this would also ensure that it is unique.
When used via `get_axes_from_description`, it currently would allow multiple matches. I'm not sure whether to disallow this or not. Opinions @Zettelkasten ? **Edit** I now changed it to require that it is unique. Otherwise it throws an error. If this does not work for the user, he should just use an explicit dim tag.
> Dim generic placeholder, any_feature_dim, any_spatial_dim

- returnn/datasets/basic.py
- returnn/datasets/util/vocabulary.py
- returnn/tf/engine.py
- returnn/tf/layers/basic.py
- returnn/util/basic.py
- tests/test_TFEngine.py
This change mainly allows to set layers with dense outputs as `search_output_layer` so that their output in included in the search output file. My main use case for this is a simple way to output confidence scores calculated in the network, but this also supports to output any other type of dense outputs like logits, hidden states, etc.
The main changes in `search` are:
- the target key does not default to `default_target` for dense outputs
- outputs without target key or that are not serialisable by the dataset are directly printed as output
> Allow search output layers without target or with dense outputs 

- returnn/tf/layers/basic.py
- returnn/tf/util/data.py
- tests/test_TFNetworkLayer.py
Currently, PostfixInTimeLayer does not work if the postfix layer input does not have a batch dim.
The problem is that using `copy_compatible_to` the batch dim is added with dim 1 and then the concatenation fails since there is a mismatch between the two batch dimension.
This change uses the unbroadcast option to expand all axes with dim 1 to the required dim.
Since we want to include the time dim (what is currently not supported by copy_compatible_to), is added the option to exclude an arbitrary axis from unbroadcasting.
> Fixes PostfixInTimeLayer to support postfix layer inputs without a batch dim

- returnn/tf/layers/basic.py
Based on the lines below, I think `param_axes` should always be a list.
> NormLayer: fix param_axes

- docs/configuration_reference/behavior_version.rst
- returnn/tf/layers/basic.py
- returnn/tf/util/data.py
- returnn/util/basic.py
- tests/test_TFNetworkLayer.py
- tests/test_TFUtil.py
Needs #863 first (which should be ready now).
Fix #666.
Introduces a new behavior version (#508) because it would break some older configs.
> Fix #666, broadcast no longer matches dims

- returnn/tf/layers/base.py
- returnn/tf/layers/basic.py
- returnn/tf/util/data.py
Before, the output name was just the first input's name.
This was very confusing when get_common_data errored because of implicit broadcasting:
Then you would think the error was in the first input,
while it was in the layer that combined the dims instead.
> get_common_data, add name parameter

- returnn/tf/util/basic.py
To support old configs using `from TFUtil import DimensionTag`. The problem is that `TFUtil` is mapped to `tf.util.basic`, but `DimensionTag` is only defined in `tf.util.data`.
Of course it is trivial to fix the config, just wanted to make you aware.
> tf.util: backwards compatibility for DimensionTag import

- returnn/datasets/audio.py
- returnn/datasets/basic.py
- returnn/datasets/cached.py
- returnn/datasets/generating.py
- returnn/datasets/lm.py
- returnn/datasets/map.py
- returnn/datasets/meta.py
- tests/test_Dataset.py
If training on huge datasets (e.g. 100M sequences), storing a full list of indices for the sequence order uses a significant amount of memory, especially when using a plain Python list and not a numpy array. With `default` sequence ordering this can be avoided by using a `range` instead. The full list is now only created after applying partition epoch, which usually means orders of magnitude less sequences.
I also made creating the sequence orderings a bit faster by using numpy. Again, with huge datasets that can make a difference. The random seed will be different, so to say, before and after this commit, not sure whether this is a problem.
Unfortunately, the code now sometimes goes back and forth between lists and arrays, but emulating `list.sort(key=...)` with numpy also wouldn't be …
> More efficient get_seq_order_for_epoch()

- returnn/tf/util/basic.py
- returnn/util/basic.py
Updated PR #875, resolving the concerns, and also fixing #890.
> Use -std=c++11 for GCC 5 and lower

- returnn/tf/layers/basic.py
I had the really peculiar issue that enabling `debug_print_layer_output_shape` would change the time dimension tag of my decoder 🙆‍♂️
That happened when using a LengthLayer (`"target_length": {"class": "length", "from": "data:classes"}`).
When `debug_print_layer_output_shape` the layer output placeholder is reset via:
```
layer.output.placeholder = py_print(
layer.output.placeholder,
...)
```
But in case of LengthLayer, `layer.output is Dim.dyn_size_ext` and thus the placeholder can have an attribute `_is_size_of_dim_tag`. This attribute however does not survive the `tf.identity()` in `py_print()`. And in the end
```
time_dim_tag = Dim.get_tag_from_size_tensor(fixed_seq_len)
assert time_dim_tag == self.time_dim_tag
```
in `_SubnetworkRecCell.get_ouput()` failed because `time_dim_tag is …
> LengthLayer: copy dim.dyn_size_ext before using as output

- returnn/tf/util/data.py
- tests/test_TFNetworkLayer.py
Consider the example (also in the test) to use `DotLayer` using a square matrix, so its two dimensions are the same.
```
from returnn.tf.util.data import batch_dim
time_dim = SpatialDim("time")
feat_dim = FeatureDim("feature", dimension=3)
config = Config({
"extern_data": {
"data": {"dim_tags": [batch_dim, time_dim, feat_dim]},
"matrix_ambiguous": {"dim_tags": [feat_dim, feat_dim], "available_for_inference": True},
},
})
```
Here, `{"class": "dot", "from": ["data:data", "data:matrix_ambiguous"], "reduce": feat_dim}` does not work because it is ambiguous.
Introducing the `Dim.match_priority` solves this problem, by having:
```
"matrix_non_ambiguous": {
"dim_tags": [feat_dim.copy(match_priority=1), feat_dim], "available_for_inference": True},
```
This was suggested here: …
> Solution for ambiguous dim tags

- returnn/tf/layers/basic.py
- returnn/tf/layers/rec.py
Fix #946.
When the `ChoiceLayer` `search` option is not set, it will fall back to the old behavior of using the network search flag.
One small behavior change, without introducing new behavior version:
- `ChoiceLayer` with `search=True` option has ignored this option before when the parent network search flag was not set. Now it will use it, ignoring the parent network search flag.
> Simplify search flag logic

- returnn/tf/layers/rec.py
- returnn/tf/network.py
- tests/test_tools.py
- tools/compile_tf_graph.py
This is PR #266 cleaned up.
This will be ongoing.
Categorization (terminology) of state vars:
- base state vars: not updated during the decoder steps. e.g. the encoder network
- loop state vars: not base and not stochastic
- stochastic state vars:
- scores
- choice
Just some summary of changes from the old PR #266 and which need to be done here:
```
update_ops_coll = tf.get_collection_ref("update_ops")
post_update_ops_coll = tf.get_collection_ref("post_update_ops")
encode_ops_coll = tf.get_collection_ref("encode_ops")
decode_ops_coll = tf.get_collection_ref("decode_ops")
decoder_input_vars_coll = tf.get_collection_ref("decoder_input_vars")
decoder_output_vars_coll = tf.get_collection_ref("decoder_output_vars")
global_vars_coll = tf.get_collection_ref("global_vars")
```
And also …
> Update compile_tf_graph.py for new RASR decoder

- returnn/tf/layers/basic.py
- returnn/tf/util/data.py
- tests/test_TFNetworkLayer.py
Fix #955 for most relevant layers, as an extension to #597.
> Allow unspecified out dim

- returnn/datasets/hdf.py
For a use case that I have in mind, I need to be able to get data from an `HDFDataset` based on the sequence tag. I added `HDFDataset.get_data_by_seq_tag()` for that purpose.
It is very similar to `HDFDataset.get_data()` which has a special case `if self.cache_byte_size_total_limit > 0`. I'm not familiar with that and not sure how to handle this here, that's why I mark this PR as draft.
> HDFDataset: add get_data_by_seq_tag

- returnn/datasets/util/feature_extraction.py
So far only the DCT parameters were controllable, but not some of the more important MFCC settings. When working with 8kHz audio, the librosa default of 128 mel filters is too large, and will result in "empty" mel filters (=filters covering less than one FFT output position).
@michelwi With this you should able to fix your issues.
> add additional params for MFCC features

- returnn/datasets/basic.py
I have a custom `Dataset` class that I would like to use in a config. The idea is to do it like
```
class MyCustomDataset(Dataset):
...
train = {"class": MyCustomDataset, ...}
```
To allow this, I added this small change of `get_dataset_class` to also allow `Dataset` inputs instead of just strings.
> get_dataset_class: allow Dataset input

- returnn/tf/util/data.py
When user defines a `"stag:<tag>"` but the `<tag>` is not a spatial dimension.
Return will throw: `tag name <tag> is not unique in dim tags`.
Which only makes sense if there where several matched dim tags, but in this case there is no matched dim tag.
This adds an assertion `len(matching_dim_tags) > 0`. Might help debugging `"in_spatial_dims"`.
Will either say "no spatial tag found with name", or "no tag found with name" if `spatial_only=False`
> Descriptive error, If no matching dim-tag was found

- returnn/tf/layers/basic.py
- returnn/tf/layers/rec.py
- returnn/tf/util/data.py
- tests/test_TFNetworkRecLayer.py
- tests/test_TFUtil.py
Fix #769. Specifically, it fixes the problem that the behavior when optimized out of a rec loop is not consistent and opaque to the user.
The `masked_from` option still is an exception though.
> Fix MaskedComputationLayer for RETURNN principles

- returnn/tf/layers/base.py
- returnn/tf/layers/basic.py
- returnn/tf/layers/rec.py
- returnn/util/basic.py
- tests/test_TFNetworkRecLayer.py
This fixes specifically `test_reclayer_optimize_out_masked_computation_out_shape` introduced in the PR.
This fixes `out_shape` usage in sub layers of the masked computation because of this logic:
```python
if "out_shape" in d:
inside_rec_time_dim = network.get_inside_rec_time_dim(inside_loop=True)
over_rec_time_dim = network.get_inside_rec_time_dim(inside_loop=False)
if over_rec_time_dim and not inside_rec_time_dim:  # moved out of loop
from returnn.tf.util.data import OptionalDim
out_shape = d["out_shape"]
if not isinstance(out_shape, set):
assert not out_shape, "out_shape %r must be empty if not a set" % (out_shape,)
out_shape = set()
out_shape.add(OptionalDim(over_rec_time_dim))
d["out_shape"] = out_shape
```
`over_rec_time_dim` is added when optimized out, however, this is not the …
> MaskedComputationLayer, fix over_rec_time_dim for sub layers

- returnn/tf/layers/basic.py
I had an issue with the `DctLayer` where the position of the time axis was not the same in input and output (we always enforce batch spatial major). This PR fixes the issue for me.
> DctLayer: fix for size_placeholder

- returnn/tf/layers/basic.py
If we use the `ActivationLayer` to get the angle of a complex input, the output dtype is not set correctly. See #537 which already fixed this issue for abs activation.
> ActivationLayer: out dtype fix for angle

- returnn/tf/network.py
Layer used "only_on_search" are currently constructed also in training if "register_as_extern_data" is set. This is a bug or at least very counter-intuitive.
(Using those flags in combination might be questionable though... I'm abusing extern data lacking knowledge of a better way to make a layer input dependent on whether it is training or search. My layer with "only_on_search" overwrites a previous "register_as_extern_data". )
> Fix 'only_on_search' ignored if 'register_as_extern_data' set

- returnn/tf/util/data.py
- tests/test_TFNetworkLayer.py
Fix #1017.
1 + x - 1 != x for dim tags, but using tf_util.simplify_* would make them equal.
Note that this might change the behavior of some older configs where the resulting dim tags would have been equal. I'm not really sure that we hit this case.
> Fix dim tags equality

- returnn/tf/util/data.py
This looks like a major bug. It could affect all more custom masking logic (`SoftmaxOverSpatialLayer`, `GenericAttentionLayer`/`DotLayer`) for custom dyn sizes (e.g. in some transducer or segmental models).
(@robin-p-schmitt But it doesn't seem to fix the problem you showed me with nan when you disable attention dropout, [config](https://gist.github.com/albertz/3de318fca54b76518e24cde024913585).)
> Data seq mask, fix for extended dyn size

- returnn/tf/util/basic.py
- returnn/tf/util/data.py
size_ext might have invalid (zero) sizes when it itself has some padding, e.g. when its own shape is dynamic.
A zero size can lead to problems in some cases, e.g. in SoftmaxOverSpatialLayer, when everything is masked to -inf, it results in nan, and this likely produces nan in backprop or elsewhere.
Thus, mask size_ext itself, and set the padded values to 1.
---
This is somewhat an unrelated or orthogonal follow-up to #1019, resulting from [this config](https://gist.github.com/albertz/3de318fca54b76518e24cde024913585).
@robin-p-schmitt This probably should fix the problem you showed me with nan when you disable attention dropout.
> Data ext seq mask, use non-zero sizes for padded ext dyn size

- returnn/datasets/sprint.py
The call `CachedDataset2.init_seq_order` always resets `self._num_seqs` so it needs to be set again even if we do not need to reinit.
If a `sequence_filter_list` is given, the `self.seq_list_ordered` might be a subset of `self.seq_list_original` (i.e. the true number of sequences is smaller) otherwise they have the same length. So it should always be save to use `len(self.seq_list_ordered)`.
> fix for SprintCacheDataset

- returnn/tf/layers/basic.py
The documentation of the reduce layer was outdated since more than just `sum` and `max` are allowed. Still kept them as examples, but maybe we can just drop the completely from there.
> Reduce Layer documentation

- pytest.ini
- returnn/tf/layers/base.py
- returnn/tf/layers/basic.py
- returnn/tf/layers/rec.py
- returnn/util/better_exchook.py
- tests/_setup_test_env.py
- tests/test_TFNetworkLayer.py
Currently it's not entirely clear what the problem is but some of the added test cases here fail.
It seems the `k_dim` is broken when the `TopKLayer` is inside a `CondLayer`.
**Edit** It was actually a bug in `CondLayer` together with subnet logic. The subnet layers were actually constructed twice because the template construction was not correctly triggered. See `test_CondLayer_subnet_template_construct`.
This PR fixes that.
---
There are some partly unrelated commits in here as well, so this PR should be rebased to keep individual commits.
> TopKLayer conditional k-dim fix

- returnn/tf/network.py
Since `CastLayer` is of instance `CopyLayer` it will be "skipped" during flattening which potentially causes dtype issues. This should fix the check, maybe its worth looking into the other subinstances of `CopyLayer` for other cases. 
From what I found these are: 
`DropoutLayer`, `ScaledGradientLayer`, `BatchNormLayer` and `TikhonovRegularizationLayer`. If you think only skipping `CopyLayer` would make sense I would change the whole check to:
`type(layer_) is CopyLayer`
Additionally I added some comments for some of the private functions of the flatten logic to make them more understandable, especially when seeing them first. 
Feel free to comment on them and make suggestions how to improve them, these are for now how I understood them and by far not perfect I think.
Also if you have a …
> Automatic flattening, fix for CopyLayer, comments

- returnn/tf/layers/basic.py
It seems there was a regression bug related to using integer axis values in `expand_dims` layers, so one of my old setups stopped working.
Not sure if my fix is correct for all cases, I first want to see the tests.
> fix passing int axis to expand_dims

- returnn/tf/util/data.py
Fix for https://github.com/rwth-i6/i6_experiments/issues/73
The check was only for batch info of the batch dim tag, but in cases where the tag has the info instead this was not working. 
I am not sure whether to actually prefer the tag batch info over the batch_dim info, but wanted to not change potential old behavior, thats why the check is for batch_dim first.
> Check for tag.batch when creating size placeholder

- returnn/sprint/cache.py
This is a straight-forward fix for the ambiguous use of the variable "typ". It is overwritten multiple times and did not retain the desired information about the alignment type. This caused undesired behavior of the SprintCacheDataset which disregarded the substate.
> sprint.cache, more clear code

- returnn/datasets/cached.py
I have a MetaDataset which combines multiple HDFDatasets. During construction, the case occurred that `self._seq_index` was a `numpy.ndarray` but `seq_index` was of type `list`.
> extend check for ndarray in CachedDataset

- returnn/datasets/basic.py
- returnn/datasets/meta.py
- returnn/tf/engine.py
- tests/test_Dataset.py
See the `_custom_chunking_func` in the test case as an example.
Alternative implementation to PR https://github.com/rwth-i6/returnn/pull/502, PR https://github.com/rwth-i6/returnn/pull/375.
Note that the decoupling as discussed in https://github.com/rwth-i6/returnn/issues/376 is still separate. I think we need further discussion on this, so let's do this in a separate step.
Anyway, we need this functionality here now. (@robin-p-schmitt specifically, for transducer. Not exactly like in #375 or #502 but we want to throw away chunks which just have blank labels.)
> `chunking` can be a custom function

- returnn/datasets/generating.py
- returnn/datasets/meta.py
- tests/test_GeneratingDataset.py
Example: you have downsampling factor 6, i.e. ceildiv(data_len, 6) == align_len.
Now it could happen that ceildiv(data_len1 + data_len2, 6) < align_len1 + align_len2.
This option would repeat intermediate ending frames such that data_len1 % 6 == 0.
Also part of this PR is some rewrite of `StaticDataset`, somewhat related to https://github.com/rwth-i6/returnn/pull/329.
> ConcatSeqsDataset, option to match alignment

- returnn/tf/layers/basic.py
- returnn/tf/native_op.py
Similar to e.g. `ctc_loss`  in `native_op.py` this adds the option to set the blank_index for the forced_align layer. Default is still the same as before (last index in the vocab). 
Also adds documentation for the parameter to a few other functions which have the same parameter.
> Option for setting blank index in forced_align Layer

- returnn/tf/layers/basic.py
This is a fix for #1086 
Since this behavior (even though its really implicit) is most likely far used the only option I saw to fix this is to add a flag.
> Option to have blank in vocab

- returnn/datasets/cached.py
- returnn/datasets/generating.py
- returnn/datasets/lm.py
- returnn/datasets/map.py
- returnn/datasets/meta.py
- returnn/datasets/numpy_dump.py
- returnn/datasets/raw_wav.py
- returnn/datasets/sprint.py
- returnn/datasets/stereo.py
- tests/test_TFEngine.py
A sampling size of 0 did not work in `CombinedDataset` with `TranslationDataset` as subdatasets because an empty `seq_order` list as parameter of `init_seq_order()` was interpreted as "no sequence order given" in `TranslationDataset`. The dataset then creates a sequence order itself with more sequences which makes the "all_sequences_used" check in `CombinedDataset._expand_dataset_sec_idxs()` fail.
I tried to fix it in all places now. Maybe a bit pedantic, but necessary at least for this special use case.
> init_seq_order: consistently treat empty seq_list/seq_order to mean 0 sequences

- returnn/datasets/sprint.py
This adds a parameter `reduce_target_factor` to the ExternSprintDataset class. This is used to modify the assertion that number of frames and number of targets are equal and checks the number of frames after subsampling by this factor instead.
An alternative solution would be to remove the assertion altogether.
> Allow subsampled targets for ExternSprintDataset

- docs/getting_started/training.rst
The section on generic scheduling currently doesn't show an example. I added one for applying gradient clipping only at the beginning of the training.
> add generic scheduling example to docs

- returnn/datasets/util/feature_extraction.py
Adds center to mfcc energy function. Tbh. I am not sure how with center=False, for the code before this change, this would work and not crash due to different shapes (librosa default is True, so I think there would be a mismatch)
This option is both in [rsme](http://man.hubwiz.com/docset/LibROSA.docset/Contents/Resources/Documents/generated/librosa.feature.rmse.html) and [rms](https://librosa.org/doc/main/generated/librosa.feature.rms.html) so also the if check should not be a problem.
> center for energy

- .github/workflows/main.yml
- returnn/torch/dataset_wrapper.py
- returnn/torch/engine.py
- tests/PyCharm.idea/inspectionProfiles/Project_Default.xml
First bit of code for PyTorch datasets, see #1120
Sorry, let me do this as a PR once, I'm unsure whether I'm running this PyCharm inspect check correctly manually...
> PyTorch: basic dataset wrapper

- returnn/tf/layers/rec.py
- returnn/util/better_exchook.py
- tests/test_TFEngine.py
Before, I got:
```
File "/Users/az/i6/setups/2022-03-19--sis-i6-exp/ext/returnn/returnn/tf/layers/rec.py", line 2391, in _SubnetworkRecCell.get_output
line: assert input_seq_len is not None, "length is not defined. provide an 'end' layer"
```
Even though I provided an existing defined `time_dim_tag`.
However, I also had some beam search inside, thus `output_template_search_choices` was set, thus the `time_dim_tag` was not used (for whatever reason). This fixes it.
> RecLayer, use existing time_dim_tag

- returnn/tf/layers/base.py
- returnn/tf/layers/basic.py
- returnn/tf/layers/rec.py
- tests/test_TFNetworkRecLayer.py
The problem arises due to the template construction logic of the RecLayer. (Related: #1129)
The templating is done multiple times, and thus the logic is flawed, to store the `_queried_sub_layers` via `get_sub_layer_out_data_from_opts`, and then later rely on the items in there as the information what sub layers were queried, because the kwargs might have been reset in the meantime.
This is not really so much an argument against the RecLayer construction logic, but it was unreliable in the first place to rely on `_queried_sub_layers` for this, and having this implicit assumption that `get_sub_layer_out_data_from_opts` must have been called before, and the same `kwargs` are used. It's bad to have such implicit assumptions.
Now the only real assumption is that we are inside a `RecLayer`, …
> MaskedComputationLayer, fix state

- docs/configuration_reference/behavior_version.rst
- returnn/tf/layers/rec.py
- returnn/util/basic.py
- tests/test_TFNetworkLayer.py
- tests/test_TFNetworkRecLayer.py
A check on matching time dim of RecLayer sub output layer to the RecLayer time dim.
Fix https://github.com/rwth-i6/returnn/issues/1140
This introduces a new behavior version 13 (https://github.com/rwth-i6/returnn/issues/508).
>  Recover relaxed behavior, strict with new behavior version

- returnn/tf/layers/rec.py
- returnn/tf/util/data.py
Also fixes `Dim.is_dynamic`. Related: #1139
Also needed for #1143.
> Dim get_size_dim_tag fix

- demos/demo-torch.config
- returnn/engine/base.py
- returnn/torch/engine.py
- returnn/util/basic.py
".pt" file extension seems standard.
I think calling `model.load_state_dict()` in each epoch is the right way to do it if we really want `get_model_func` to be specific to the epoch. Although this probably has to be extended if the set of model parameters really changes between epochs.
The demo now carries over the model state between model epochs, saves model files, and can be interrupted and continued.
> PyTorch: save/load models

- returnn/tf/engine.py
- returnn/tf/util/data.py
- tests/test_TFNetworkLayer.py
- tests/test_TFUtil.py
Don't first create a new size placeholder and then later call `declare_same_as`.
Esp this is required when `declare_same_as` becomes stricter (#1143).
> Data same_dim_tags_as fix auto_create_placeholders

- returnn/datasets/basic.py
If we have dataset keys with different length specify chunk_size and chunk_step as dicts we might also want to specify the min_chunk_size as a dict with different sizes per key.
> add option to specify min_chunk_size as dict

- returnn/tf/layers/signal_processing.py
The original code did not work without eager execution mode. And even then the if statement does not work element-wise over the batch dim.
This now makes use of  integer division round up.
```
int(ceil(x / float(y))) -> (x-1)/y + 1
```
> fix option stft-pad_last_frame in MultiChannelMultiResolutionStftLayer

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
Fix #1207.
It's a bit strange. So far I just removed code. The removed code triggered test_CondLayer_mult_dyn_axes to fail, and now it works.
The code anyway was a bit strange.
I wonder where it really was needed?
Maybe we actually don't really support the case when a dim tag is created inside the CondLayer?
If it turns out we need it, we should have a test case for it to make sure we get it right.
> CondLayer, fix support for multiple dyn axes

- returnn/tf/layers/rec.py
- tests/test_TFNetworkRecLayer.py
This is the case for beam search on a CTC model. The choice of a label in one frame is independent from the earlier labels.
Attempt to fix/implement:
```
...
Rec layer 'loop' (search True, train False) sub net:
Input layers moved out of loop: (#: 2)
rec_unstack
log_prob
Output layers moved out of loop: (#: 1)
output
Layers in loop: (#: 1)
choice
Unused layers: (#: 0)
None
layer /loop(rec-subnet-input)/'rec_unstack': [B,T|'time'[B],F|F'enc'(10)] float32
layer /loop(rec-subnet-input)/'log_prob': [B,T|'time'[B],F|F'classes'(3)] float32
layer /loop(rec-subnet)/'log_prob': [B,F|F'classes'(3)] float32
layer /loop(rec-subnet)/'choice': [B&Beam{'loop/choice'}(3)] int32 sparse_dim=Dim{F'classes'(3)}
debug search choices:
base: <ChoiceLayer loop/'choice' out_type=Data{[B&Beam{'loop/choice'}(3)], …
```
> ChoiceLayer in loop without dep

- docs/configuration_reference/behavior_version.rst
- returnn/tf/layers/base.py
- returnn/tf/network.py
- returnn/tf/updater.py
- returnn/tf/util/basic.py
- returnn/util/basic.py
- tests/test_TFNetworkLayer.py
- tests/test_TFNetworkRecLayer.py
- tests/test_TFUpdater.py
The decoupled constraints are calculated in a more direct way, not using the SGD optimizer. This should make it (much) more efficient (at compilation time), while being equivalent otherwise. But I actually had memory problems and this solved it.
I also fixed/changed the logic of decoupled constraints when used with gradient accumulation: With gradient accumulation N, the constraints are only applied every Nth step. This is because this is actually equivalent if you would increase the batch size by N instead of using gradient accumulation.
Along the way, I discovered and fixed non-deterministic behavior on global train step incr and read order, which potentially has an effect on gradient accumulation (#1205). Thus it introduces the new behavior version 15 for this. Note that this is …
> Decoupled constraints better, grad accum and others deterministic

- returnn/tf/layers/basic.py
The `ConvLayer` implements depthwise convolution via `tf.nn.depthwise_conv2d`. This is used in a testcase in https://github.com/rwth-i6/pytorch-to-returnn/pull/128.
There are currently two issues:
1) It seems to me that the strides are confused for `"NCHW"` and `"NHWC"`.
2) When we actually have a 1D case, an additional dim is added and still `tf.nn.depthwise_conv2d` is used. An additional stride of 1 is added for this dim. However, I get
```
InvalidArgumentError: Current implementation only supports equal length strides in the row and column dimensions.
```
in this case. Since the added dim is anyway 1, we can also have the same stride as for the spatial dim which is then supported.
> fixes for depthwise 1d conv

- returnn/tf/network.py
- tests/test_TFNetworkLayer.py
Causes by some returnn_common experiment. Reproduced in `test_CondLayer_outside_layer_access`.
I got a very strange `LayerNotFound` exception, which seems triggered by some combination of `RecLayer` and `CondLayer`. The layer construction recursively goes from the output layer to the rec subnet template construction to the cond layer and then to the base network to access some parameters which are in a subnet of the base network. This fails:
```
...
File "/Users/az/i6/setups/2022-03-19--sis-i6-exp/ext/returnn/returnn/tf/layers/base.py", line 621, in <listcomp>
line: get_layer(src_name)
locals:
get_layer = <local> <GetLayer '/cond(false_layer)/cond/encoder/self_att/qkv' parent_get_layer=<GetLayer '/cond(false_layer)/cond/encoder/self_att' parent_get_layer=<GetLayer …
```
> CondLayer fix LayerNotFound

- returnn/datasets/meta.py
Just a more verbose error message for some issue I stumbled upon when using an `LmDataset` within a `MetaDataset`.
> verbose error for invalid datasets

- returnn/datasets/lm.py
The default output vocabulary of the https://github.com/rwth-i6/subword-nmt repo is a python formatted dictionary in text form. The `OggZipDataset` can use it, but the `LMDataset` did not yet, so I added that capability.
> Allow text-dict style vocab on LM Dataset

- returnn/util/basic.py
Currently, `obj_diff_list` does not work for numpy arrays. I had an issue with `get_network()` which outputs a network including an array. 
Example test case to reproduce the error:
```
def test_get_network_with_arrays():
from returnn.config import Config
from returnn.tf.engine import Engine
from returnn.datasets import init_dataset
from returnn.tf.util.data import batch_dim, SpatialDim, FeatureDim
time_dim = SpatialDim('time')
in_dim = FeatureDim('in', 3)
out_dim = FeatureDim('out', 4)
def _config_get_network(epoch, **_kwargs):
net_dict = {
"fw0": {"class": "linear", "n_out": 10, "from": "data"},
"constant": {"class": "constant", 'value': numpy.array([0, 1, 2])},
"output": {"class": "reduce", "mode": "mean", "axes": ["B", "T", "F"], "loss": "as_is", "from": "fw0"}
}
return net_dict …
```
> fix obj_diff_list for numpy arrays

- returnn/tf/util/data.py
It is already possible to use axis descriptions for spatial tags like `"axis": "stag:<...>"`. I'd like to add that functionality for static dims as well, e.g. via `"axis": "tag:<...>"` for any tag.
> axis description for any tag

- returnn/tf/layers/base.py
- returnn/tf/layers/basic.py
- returnn/tf/layers/rec.py
- returnn/tf/network.py
- returnn/tf/util/data.py
- tests/test_TFNetworkLayer.py
- tests/test_TFUtil.py
- tests/test_tools.py
- tools/compile_tf_graph.py
"Defined" here means that `dyn_size_ext` is set for dynamic sizes. This can be a template (no `placeholder`). But the shape is important. Usually [B] but not always.
Returnn-common requires this but this should be consistent anyway.
The first commit adds this to the `Data.sanity_check`.
A number of layers don't do this correctly. Namely:
A few other things broke because of this. This is again a reminder for https://github.com/rwth-i6/returnn/issues/975...
> require dim tags to be defined

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
When some dim was initially created inside a CondLayer, it had the wrong control flow context.
This lead to the error:
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[0] does not have value
```
This fixes it.
> ReinterpretDataLayer, fix dyn_size_ext placeholder context

- returnn/frontend_api.py
- returnn/tensor/_dim_extra.py
- returnn/tensor/_tensor_extra.py
- returnn/tensor/dim.py
- returnn/tensor/tensor.py
- returnn/tf/frontend_layers/frontend.py
- returnn/tf/frontend_low_level/frontend.py
- returnn/tf/layers/base.py
- returnn/tf/layers/basic.py
- returnn/tf/layers/rec.py
- returnn/tf/layers/signal_processing.py
- returnn/tf/util/basic.py
- returnn/tf/util/data.py
- returnn/torch/frontend/frontend.py
- returnn/util/basic.py
- tests/test_TFNetworkLayer.py
- tests/test_TFNetworkRecLayer.py
- tests/test_TFUtil.py
* This moves `Data` and `Dim` to a more central place `returnn.tensor`
* Rename `Data` to `Tensor`.
* Abstracts away from TF specific code, and allows for any raw tensor type. This is via the new frontends.
* Separates the core of `Tensor` to additional attribs in `_TensorExtra` which is mostly only needed for legacy code, and most methods are in `_TensorMixin`. Similarly for `Dim`. To the user, these are implementation details and should not matter. For a new user interested in `Tensor`/`Dim`, it should be enough to just look the main classes.
* Fix #1165.
* Fix #1260.
* Related: #975.
> Tensor abstraction

- returnn/tensor/_dim_extra.py
- tests/test_TFUtil.py
In _post_init_output, this would have overwritten some valid dim tags by wrong ones. E.g. when the valid shape was [1+T,B], and there was a target set with shape [T,B],
it would replace 1+T by T.
> get_all_dimension_tags, don't prefer derived bases

- returnn/__main__.py
- returnn/datasets/basic.py
- tests/test_TFEngine.py
Using default value 0 is not a good idea. Also i had a job where i did not set the `forward_batch_size` and the job got stuck with default value 0.
> Set forward batch size explicitly for task Search

- returnn/torch/engine.py
As discussed in https://github.com/rwth-i6/returnn/issues/1120, `preload_from_files` or something equivalent should be added for the PT engine as well. This is certainly not complete, but could be helpful as a starting point. It works as a proof-of-concept to load a wav2vec 2.0 checkpoint.
What do you think in general?
> preload_from_files for PT engine

- returnn/tensor/_tensor_extra.py
- returnn/tf/engine.py
When I got the exception for mismatching shapes of raw tensor vs. tensor, the printed output was very large and I guess just the shape is needed, right? The other change is just a typo.
> Fix Error Messages

- returnn/datasets/hdf.py
We convert the dtype to `str` but then in the assertion try comparing for equality with the original, uncoverted type. This assertion triggered for me even though it does not seem right.
> fix: Correct assertion on HDF data dtype

- returnn/tensor/_dim_extra.py
- returnn/tf/util/basic.py
Changes the old `ceildiv_right(a, b)` to `⌈a/b⌉`.
Example: `conv dim: Dim{'⌈(-1+time+-2)/3⌉'[B]} time dim: Dim{'time'[B]}`
> Dim ceildiv nicer description

- returnn/torch/updater.py
Should only add one parameter to the weight decay set if two or more modules share common parameters.
Fix #1319.
> PT weight_decay fix for shared params

- returnn/__main__.py
- returnn/datasets/basic.py
- returnn/log.py
- returnn/torch/distributed.py
- returnn/torch/engine.py
For PyTorch (#1120).
1. Multi GPU training with `DistributedDataParallel`
2. Gradient accumulation
3. Add elapsed training time for each sub-epoch
Fix #1332.
Question: how do we set the multi-GPU flag in the returnn config?  I saw for the automated mix precision, the opts dict should be defined in the returnn config. Should I also use a dict opts for the DistributedDataParallel in the returnn config? So that we can define parameters like `bucket_cap_mb`, `find_unused_parameters` in the opts dict?
> PyTorch DistributedDataParallel Multi-GPU training

- returnn/tensor/_dim_extra.py
- returnn/tensor/_tensor_extra.py
- returnn/tensor/tensor_dict.py
- returnn/tf/frontend_layers/config_entry_points.py
- returnn/tf/layers/variable.py
- tests/rf_utils.py
- tests/test_TFNetworkLayer.py
https://github.com/rwth-i6/returnn/issues/1333#issuecomment-1563052008
https://github.com/rwth-i6/returnn/issues/1333#issuecomment-1590965034
It was mentioned that the recreation of the batch dim was unexpected and caused problems because in PyTorch engine, we would set the `dyn_size_ext` of the batch dim, and otherwise not use the batch info mechanism, so a separate instance of such dim tag would not correctly have the `dyn_size_ext`. The recreation happens here: https://github.com/rwth-i6/returnn/blob/04c14d6a3745f90f0bd10b28ce4d51b1d61afb82/returnn/tensor/_tensor_extra.py#L3577
This is only for `model_outputs`.
It is anyway a bit bad that we have all that special handling for batch dim tags, so that the behavior depends so much on the dim tag type.
> Reuse global batch dim

- returnn/torch/data/pipeline.py
- returnn/torch/engine.py
- tests/test_torch_engine.py
This PR adds `min_seq_length` and `max_seq_length` as parameters to the torch configs, similar to tensorflow.
> Min and max seq len for Pytorch

- returnn/datasets/meta.py
This is required by `MultiProcDataset._seq_order_proc_loop` https://github.com/rwth-i6/returnn/blob/1cee4aa1dadb1e216b9311dd65d4753753b7beb6/returnn/datasets/multi_proc.py#L131
> Add get_current_seq_order to MetaDataset

- returnn/torch/distributed.py
- returnn/torch/engine.py
This PR enables both nccl and gloo backend for torch.distributed. The gloo backend will be used for collectives with CPU tensors and the nccl backend will be used for collectives with CUDA tensors. Before this PR, we only used nccl backend which is only  available with CUDA tensors. Thus for the has_data all reduce operation at the beginning of each training step iteration, we have to make a roundtrip to send has_data Tensor through CPU -> GPU -> NCCL -> GPU -> CPU, which is very inefficient.  With this PR, gloo backed is available for the CPU tensors. Therefore, has_data all reduce can be operated on cpu directly and save the detour.
> enable both gloo and nccl backend for torch distributed

- returnn/tf/layers/rec.py
Related for #1248.
Compilation would also work without this, but it would crash at runtime without this.
> TF SelfAttentionLayer fix initial state outside loop

- tests/test_TFNetworkRecLayer.py
This was to debug an issue we had where two implementations were supposed to return the same but they did not.
We have some left context, which we want to add to the keys and values, but not to the queries.
We can either implement self-attention by hand, or use the layer, but for the layer, it operates on the whole sequence, so it would calculate unnecessary queries for the left context, and we would then slice the output. So via the layer, it would be less efficient.
This test is to compare both outputs for equality.
Additionally, it uses relative positional encoding.
It's good to have this test also in RETURNN directly, as a sanity check for `SelfAttentionLayer` and `RelativePositionalEncodingLayer`.
To summarize the issue we had: We did the parameter import wrongly. See the code in the …
> test_rel_pos_self_attention_left_ctx_explicit_vs_layer

- returnn/torch/engine.py
- returnn/torch/updater.py
This PR enables the user to define a custom dynamic learning rate function in the returnn config. At each train step, the current step learning rate will be then calculated based on the dynamic learning rate function and updated at each step. 
One example of the dynamic learning rate function would look like this
```
def dynamic_learning_rate(*, global_train_step, learning_rate, **kwargs):
max_lr = 5e-4
end_lr = 1e-8
total_num_updates = 400000 * 3
num_warm_up = total_num_updates * 0.2
if global_train_step <= num_warm_up:
warmup_factor = global_train_step / num_warm_up
lr = warmup_factor * max_lr
elif global_train_step > total_num_updates:
lr = end_lr
else:
lr_range = max_lr - end_lr
pct_remaining = 1 - (global_train_step - num_warm_up) / (
total_num_updates - num_warm_up
)
lr = lr_range * …
```
> PT dynamic_learning_rate support

- returnn/torch/engine.py
This PR was originally pull request #1359. I accidentally closed that PR, so I reopened it again here, I am sorry for the inconvenience.
@albertz I now set 
```
if model_epoch_filename:
...
is_training = self.config.value("task", "train") == "train"
is_first_train_epoch = not epoch and (is_training or self.config.value("task", "train") == "initialize_model")
if not model_epoch_filename:
step = 0
epoch = self._start_epoch or 1
```
because otherwise for the case not model_epoch_filename and not is_first_train_epoch, the step and epoch is still None and we will get error in line `random_seed = (epoch * 193939 + step * 19937 + random_seed * 27644437 + 479001599) % (2**31)`
> fix the is_first_train_epoch check for preload_from_files 

- tools/torch_export_to_onnx.py
When running this script in a CPU-only image, I got
```
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu
') to map your storages to the CPU.
```
even though I specified `--device cpu`. This PR should fix this.
> torch onnx export: load model on device

- returnn/torch/engine.py
In TF, the total number of model parameters was printed at startup. I think it would be nice to add this for the torch engine, too.
> PyTorch engine: print total number of model params

- .github/workflows/main.yml
- demos/demo-rf.config
- demos/demo-torch.config
- returnn/frontend/run_ctx.py
- returnn/tensor/tensor_dict.py
- tests/rf_utils.py
- tests/test_demos.py
- tools/torch_export_to_onnx.py
This implements proper dynamic dims handling as it was discussed #1333. It also extends some test cases and documentation.
- Test cases: Also perform ONNX inference on the exported ONNX models.
- Handle `available_for_inference` in `extern_data`: They are excluded.
- Handle duplicated dims in `extern_data`: Only the first is used. (First according to the order defined by the dict in the config.)
- Handle scalar dynamic dims in `extern_data` and `model_outputs`: They are excluded.
- It is an error if some dim `dyn_size_ext` in `model_outputs` is specified as not being a scalar (e.g. common seq lens of shape [B]) but its value is not defined.
- Demos are adapted.
- Torch-to-ONNX export documentation extended.
> Torch ONNX export, proper dynamic dims handling

- returnn/sprint/cache.py
As discussed in https://github.com/rwth-i6/i6_core/pull/434 here are the changes to update the corresponding code in returnn.
I found some more changes missing here, so I added them as well.
Overview of additions:
* Allows to sent an encoding to read and write segment names
* Support for weighted alignments
* Failsafe for empty feature sequence.
> Add updates from i6_core to sprint/cache.py

- returnn/tensor/_dim_extra.py
- returnn/tensor/_tensor_extra.py
- tests/test_TFUtil.py
Auto-generated dims are those via the legacy n_out or all other internal dims.
Any dim tags created explicitly by the user should never be treated as broadcast dims.
See also #666.
> Dim broadcasting only allowed for auto-generated dims

- returnn/tf/layers/base.py
- returnn/tf/network.py
- tests/test_TFNetworkLayer.py
This fixes combinations of reuse_params with other param transformations like param dropout.
Along the way, I also fixed and extended the flatten layer with losses a bit, as the test case triggered some problems there. I would suggest to rebase and not squash.
> TF layer var scope, fix derived custom getter

- returnn/frontend/_backend.py
- returnn/frontend/_native/__init__.py
- returnn/frontend/_native/backend.cpp
- returnn/frontend/_native/backend.hpp
- returnn/frontend/_native/module.cpp
- returnn/frontend/_native/module.hpp
- returnn/frontend/_native/py_utils.hpp
- returnn/frontend/_native/tensor_ops.cpp
- returnn/frontend/_native/tensor_ops.hpp
- returnn/frontend/_utils.py
- returnn/frontend/audio/specaugment.py
- returnn/tensor/_dim_extra.py
- returnn/tensor/_tensor_extra.py
- returnn/tensor/_tensor_op_overloads.py
- returnn/tensor/tensor.py
- returnn/torch/frontend/_backend.py
- returnn/torch/frontend/raw_ops.py
- returnn/util/py_ext_mod_compiler.py
- tests/_setup_test_env.py
- tests/test_rf_loop.py
- tests/test_torch_frontend.py
- tests/test_torch_internal_frontend.py
Some of the most often called functions (`Tensor._raw_backend`, `rf.combine`, `rf.compare`, etc) are replaced by native pure C++ implementations.
For #1402.
I think this is good already for this PR, and already shows great speedup. We can do further work in other separate PRs.
> RETURNN frontend native helpers

- returnn/frontend/_native/module.cpp
- returnn/tensor/_dim_extra.py
> Dim complete_dyn_size, better combine ops

- returnn/tensor/_dim_extra.py
Speed up eager execution (#1402) by simplifying `Dim.__hash__` and `Dim.__eq__` by not using a separate check on `derived_from_op` (dim math #853).
The dim math cache (#1416) was another preparation for this, which leads to dim equality in many cases where we had the special equality check on `derived_from_op` before.
This also simplifies the dim tag internals a bit (see #975) (although, the caching logic also made it more complex on the other side, so #975 is still open and relevant, although not really sure how to do that).
> Dim equality without derived_from_op logic

- returnn/tf/layers/basic.py
- returnn/tf/layers/signal_processing.py
As for other layers, this adds the 'use_time_mask' parameter to the ConvLayer, PoolLayer, TransposedConvLayer, StftLayer and IstftLayer.
Additionally, we add the 'same_static' option for the padding parameter of the ConvLayer and PoolLayer. This padding leads to the same output dims as 'same' padding but changes the left/right distribution of the padding for dynamic axes (i.e. see documentation of ConvLayer). We add this to guarantee that the convolution and pooling operations lead to the same output for single seqs and batched seqs, which previously was not the case.
> ConvLayer and co: use_time_mask and same_static padding

- returnn/datasets/basic.py
- returnn/datasets/cached2.py
- returnn/datasets/lm.py
Should fix #1441.
Also:
CachedDataset2 num_seqs 0 if not initialized.
CachedDataset2 is_less_than_num_seqs same.
Dataset have_seqs more correct.
> LmDataset get_total_num_seqs

- returnn/tensor/_dim_extra.py
- returnn/tf/frontend_low_level/_backend.py
- returnn/tf/util/basic.py
- returnn/util/basic.py
Add the suggestion by Albert, which resolves #1328 
I'm actually not sure if this is how its supposed to be/correct (at least it works), please let me know.
> TF: add onnx_export option and onnx_comp_floor_div

- returnn/torch/engine.py
Fix #1454.
- get dev dataloader iterator for all training processes to allow synchronization
- remove unused imports
> fix torch multi-gpu training hanging and timeout problem 

- returnn/torch/data/pipeline.py
`RasrAlignmentDumpHDFJob` at https://github.com/rwth-i6/i6_core/blob/74d328f09276447aa9401292dc6b2ec4230f5f9c/returnn/hdf.py#L332 dumps alignment cache hdfs files in `np.uint16` which failed torch tensor create at https://github.com/rwth-i6/returnn/blob/a0453738dba7ee9e85460d8237a65cbd2f24b880/returnn/torch/data/pipeline.py#L33.
> convert np.uint16 to np.int32 to allow torch tensor creation

- returnn/datasets/hdf.py
I have an `HDFDataset` with `"classes": {"dim": 88, "dtype": "uint16", "sparse": True}`. Currently, the sparsity check returns `False` because of the `uint`.
> fix HDFDataset.is_data_sparse

- tools/torch_avg_checkpoints.py
Currently the tool uses the flag `mmap` which was only introduced in torch 2.1.0. 
This change makes the tool also useable with versions below 2.1.0.
> Check for torch version before average

- returnn/datasets/audio.py
Removed a line that slows things down when seq_list is large, while not breaking anything. When seq_list is large, it takes a long time to check whether each item is in the list. Also, it doesn't hurt to create a full seq_name:data_index dictionary.
> OggZipDataset, speed up init_seq_order with given seq_list

- tools/torch_avg_checkpoints.py
I encountered this weird issue that this line would crash with `RuntimeError: result type Float can't be cast to the desired output type Long` when `out_model_state[k]` was of type `int64`. 
Can be reproduced like:
```
import torch
x = torch.Tensor([1]).to(torch.int64)
x /= 1
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
RuntimeError: result type Float can't be cast to the desired output type Long
```
Not doing the short form but instead `x  = x / 1` works.
> Remove shortform of averaging in average tool

- returnn/datasets/hdf.py
Helps in managing the training of big datasets (#1519).
Tests in a big dataset (1000 - 2000 HDF files, ~28 M segments) show that the time taken went from 50 minutes down to 15 minutes (approximately).
This code has been previously tested with an assertion that all file indices returned by the current implementation should be equal to those returned by the previous implementation. Either way, I think the implementation makes enough sense by itself.
As per `numpy.searchsorted` vs `bisect.bisect`, I looked into this, and it seems that `searchsorted` fails to give the best performance in single searches nested in a loop (as shown [here](https://stackoverflow.com/questions/62753467/is-python-bisect-faster-than-numpy-searchsorted)), which is pretty much the current use case. Either way, I …
> HDFDataset, use bisect in _get_file_index()

- returnn/__main__.py
- returnn/datasets/basic.py
- returnn/datasets/distrib_files.py
- returnn/util/file_cache.py
- tests/test_Util.py
* Fix #1544.
* Fix #1549.
* Closes #1545
Let me know your thoughts about the implementation here. I'm not a big fan yet about having to register "from the outside" the files to be released later, but I'm also not sure if there's a better way to unregister the files when the dataset is deinitialized.
One advantage realising support this way is that cache operations for the preloaded subepoch in `DistributeFilesDataset` are now actually happening asynchronously, because `init_dataset`, which invokes caching, is called in the subprocess. Previously this caching would happen in the parent process, blocking training.
> `FileCache`: add generic support for all datasets

- returnn/torch/data/pipeline.py
Not sure if I need to mention the specific issue this works around, but I think it's worth having mentioned that this not only improves performance, but also works around bugs.
I made this a PR and not a direct commit to master to bikeshed the text.
> Add warning for not using `num_workers > 0` in torch

- returnn/torch/engine.py
Closes #1565 
This PR adds a config flag to set that the existing logic for keeping checkpoints around is applied to the optimizer states as well, i.e. the optimizer states are kept just like the checkpoints. This makes working w/ long-running trainings more consistent where we want to branch off at intermediate points.
Not sure if this works yet, hence draft.
> Torch: optionally apply `cleanup_old_models` logic to optimizer states

- returnn/datasets/meta.py
To allow training with alignments of raw wav data, we make sure every concatenated sequence has strictly aligned length
> ConcatSeqsDataset pad_narrow_data_to_multiple_of_target_len

- .github/workflows/main.yml
- returnn/torch/util/gradient_checkpoint.py
- tests/test_torch_util.py
> Torch gradient_checkpoint_scope

- .github/workflows/main.yml
- returnn/frontend/__init__.py
- returnn/frontend/_backend.py
- returnn/frontend/gradient.py
- returnn/frontend/parametrizations.py
- returnn/frontend/parametrize.py
- returnn/torch/frontend/_backend.py
- tests/test_rf_base.py
Fix #1518.
* Add `rf.gradient_checkpoint_scope`.
* Add `rf.register_parametrization`, similarly as in PyTorch.
* Add `rf.weight_dropout` and `rf.weight_noise`.
> RF: weight parametrization

- returnn/frontend/array_.py
- returnn/torch/util/array_.py
- tests/test_torch_frontend.py
Follow-up to #1586, #1584.
<s>Specifically https://github.com/rwth-i6/returnn/pull/1586#issuecomment-2239162301. Specifically, add this to `rf.pack_padded`:
```python
if not out_dim:
out_dim = Dim(rf.num_elements_of_shape(dims), name="packed")
```
This allows to use a more efficient `masked_select` and custom `nonzero` variant where we can avoid a CUDA host-device synchronization.</s>
Actually, we don't do this. We even removed this code path from the RF PT `masked_select`, because it seems to be slightly slower in my benchmarks.
We might reconsider this later. Let's also see here: https://github.com/pytorch/pytorch/issues/131256
> Torch masked_select, no custom nonzero for now

- returnn/torch/updater.py
fixes #1590
according to https://pytorch.org/docs/stable/notes/amp_examples.html#working-with-unscaled-gradients gradients should be unscaled before applying gradient clipping.
> Torch: unscale gradients before noise and clipping

- returnn/torch/engine.py
Fix #1567.
For cross-validation the batch_size can be much larger compared to training.
This allows to define a custom batch_size for each dataset.
> Torch: allow setting custom batch_size for each dataset

- returnn/datasets/audio.py
- No longer relies on `init_seq_order` for data shape/type accessors to be callable
- No longer output dummy data w/ wrong shape
- No longer define `num_outputs["data"]` when no features are extracted.
Pulled out from #1596
> OggZipDataset various fixes

- returnn/datasets/postprocessing.py
- tests/test_Dataset.py
Alternative implementation to #1604 based solely on "RETURNN userland". The iterator can be imported into a RETURNN config like `from returnn.datasets.postprocessing import LaplaceOrdering` and then used.
Closes #1604
> `PostprocessingDataset`: add laplace ordering `map_seq_stream` iterator

- returnn/datasets/postprocessing.py
- tests/test_Dataset.py
Makes a common pattern much easier.
@albertz Any comments on the added docs?
> `PostprocessingDataset`: add composition function

- returnn/torch/engine.py
- returnn/torch/frontend/bridge.py
- returnn/torch/util/module.py
- tests/test_torch_frontend.py
Two features here (maybe we can also leave the individual commits as is):
Explicitly specify some parameters which should be randomly initialized (thus `filename=None`) in training.
Note: Currently, if you start training (initial epoch 1), and there is `preload_from_files`, then if that does not cover all model parameters, it will exit with the error: "Missing key(s) in state_dict: ... Any missing key is an error.". I.e. the expectation is, once `preload_from_files` is used, that covers all model parameters.
In further training epochs, when an existing checkpoint is loaded, it will also do the check, but only for those params which are not already in the previous checkpoint. The same logic also applies also for recognition.
So, when you want to use `preload_from_files` for training to …
> PT preload_from_files ext: random init, external part

- returnn/datasets/postprocessing.py
- tests/test_Dataset.py
Closes #1622
I added an assertion to make sure the seq_tags are not lost. Do we want this, or should we be lenient here? I think the breakage's impact to people from adding this assertion is rather limited.
> `PostprocessingDataset`: pass along `seq_tag`

- returnn/datasets/audio.py
- returnn/datasets/lm.py
- returnn/datasets/meta.py
This PR removes some some usage of `num_outputs` in the dataset implementations. This PR is a collection of works and best reviewed and merged on a commit-by-commit basis.
I'm going to extend this further.
Part of #1302
> Remove some usages of `num_output`

- returnn/__main__.py
- returnn/datasets/meta.py
- returnn/engine/base.py
- returnn/torch/engine.py
- tests/test_Dataset.py
- tests/test_torch_engine.py
This is mostly about `MultiEpochDataset`. The other things are minor. They are somewhat related, but maybe we can not stash them together.
> MultiEpochDataset, and some other smaller things

- returnn/util/file_cache.py
After this change there are no more intermediate FS operations after we acquire the lock file and before we start updating its mtime. If the FS is slow this could help the lockfile stay non-stale.
> FileCache: update mtime of lockfile immediately after acquiring it

- returnn/datasets/multi_proc.py
- returnn/datasets/postprocessing.py
This PR makes wrapping a MultiProcDataset into a PPDataset possible
Previously the least you'd get is this crash:
```
EXCEPTION
Traceback (most recent call last):
File "/[...]/work/i6_core/tools/git/CloneGitRepositoryJob.L2lZBnhLY2SW/output/returnn/rnn.py", line 11, in <module>
line: main()
locals:
main = <local> <function main at 0x7f8117bb7010>
File "/[...]/recipe/returnn/returnn/__main__.py", line 740, in main
line: init(command_line_options=argv[1:])
locals:
init = <global> <function init at 0x7f8117bb6d40>
command_line_options = <not found>
argv = <local> ['/[...]/work/i6_core/tools/git/CloneGitRepositoryJob.L2lZBnhLY2SW/output/returnn/rnn.py', '/[...]/work/i6_core/returnn/training/ReturnnTrainingJob.v52PWHM5t44W/output/returnn.config'], _[0]: {len = 129}
File …
```
> `MPDataset`: make compatible with being wrapped in `PPDataset`

- returnn/datasets/postprocessing.py
Closes #1651 by disallowing `seq_order` and` seq_list` when`map_set_stream` is set, and otherwise validating the `seq_list`. Not sure if the set inclusivity test is not too expensive after all.
> `PPDataset`: be strict about `seq_order` and `seq_list` in `init_seq_order`

- returnn/torch/engine.py
I first had an impl based on another data pipe, but that was cumbersome to integrate w/ per-step and per-subepoch logging, so the logic resides in the engine now. It's not too much anyway.
> PT: print padding amount per batch and subepoch

- .github/workflows/black.yml
- .github/workflows/main.yml
- .github/workflows/publish.yml
actions/cache@v2 will be [deprecated early next year](https://github.blog/changelog/2024-09-16-notice-of-upcoming-deprecations-and-changes-in-github-actions-services/)
> Bump github action versions to their most recent version

- returnn/torch/data/pipeline.py
- returnn/torch/engine.py
Support bucket batching, and other custom batching schemes, via the config option `torch_batching`.
E.g. put this into the config for bucket batching:
```python
torch_batching = {
"class": "BucketOrderingIterDataPipe",
"buckets": [(1000, 100), (2000, 50), (4000, 25), (10_000, 10), (100_000, 1)],
"length_key": "data"
}
```
This will have 5 buckets (specified as (max_seq_len, num_seqs) tuples), using seq length from "data" key.
> PT: allow custom batching, add bucket batching

- returnn/engine/base.py
I have a model with 2 losses applied in consecutive epochs. When now a score is not present in the checkpoints anymore the `min==max` check fails because the list is empty. This check fixes it, by checking first if it is empty.
> Check for empty score in cleanup

- returnn/frontend/_backend.py
- returnn/frontend/array_.py
- returnn/frontend/attention.py
- returnn/frontend/dims.py
- returnn/tf/frontend_layers/_backend.py
- returnn/tf/layers/basic.py
- returnn/torch/frontend/_backend.py
- tests/test_rf_array.py
- tests/test_rf_attention.py
- tests/test_rf_encoder_conformer.py
(This is just here to at least run the test once before I merge it into main.)
(The other commits accidentally went into here, but it cannot hurt. Let's just not squash them together but rebase then.)
> RF cum_concat_step simplify and other RF things

- returnn/datasets/distrib_files.py
- tests/test_Dataset.py
I ran into this bug when I added the same file into the "files" list of DistributeFilesDataset multiple times, which messed up the distribution over the subepochs. Subepochs 1-299 contained 1-2 files, and subepoch 300 contained over 50.
> Fix _distribute_evenly_by_size for duplicate entries in files_order

- .github/workflows/main.yml
- returnn/util/debug.py
- tests/test_threading.py
Now that we have py3.8 we can implement this.
Closes #1667
> Interrupt main thread on Exception in sub thread

- returnn/datasets/postprocessing.py
I'm open to adjusting the name of the variable
My use case for this is to get Laplace Ordering on a Dataset, so map_seq_stream wouldn't drop any sequences.
> Add option to passthrough num_seqs in PostprocessingDataset

- returnn/datasets/postprocessing.py
This assert wrongfully throws in an edge case: When the datasets' `num_seqs` is a multiple of `self.num_seqs_per_bin`, then the `seq_buffer` is replaced with an empty list in line 389, and on the next iteration `has_ended` will thus not be set because the for-loop is never entered, and this assert is triggered
> Fix assert in LaplaceOrdering

- .github/workflows/publish.yml
- pyproject.toml
- setup.py
You have mixed up build-time and run-time requirements.  Direct invocation of setup.py is [deprecated](https://packaging.python.org/en/latest/discussions/setup-py-deprecated/).  Build and publish wheels.
> fix build, publish wheels

- tools/bliss-to-ogg-zip.py
This is helpful to convert mixed-bandwidth source datasets to a uniform training bandwidth.
> OggZip: add option to resample audio via ffmpeg

- returnn/torch/distributed.py
- returnn/util/basic.py
I checked for imports from `torch.distributed` and all of them that are relevant for this PR point to `returnn.torch.distributed` now.
> PT: pass dist rank/size via env to subprocesses

- docs/configuration_reference/behavior_version.rst
- returnn/frontend/array_.py
- returnn/frontend/conv.py
- returnn/frontend/dims.py
- returnn/frontend/normalization.py
- returnn/frontend/signal.py
- returnn/util/basic.py
- tests/test_rf_array.py
- tests/test_rf_encoder_conformer.py
`use_mask` option implemented for:
* `Conv1d.__init__` and co, `conv`
* `TransposedConv1d.__init__` an co, `transposed_conv`
* `pool`, `max_pool`, `pool1d` and co
* `stft`
* `window`
* `scatter`
`rf_use_mask: bool` config option to explicitly specify the default for `use_mask`.
If `rf_use_mask` is not specified, for older behavior versions (<=22), we use `use_mask=False` by default, with behavior version >=23, we use `use_mask=True` by default. Thus this introduces the new behavior version 23.
`BatchNorm` `use_mask` is not required to be set now. If it is not explicitly set, it is True by default. (Previously, it was required to set this when there were dynamic dims, so this change does not change the behavior of any existing setup.)
Fix #1691
> RF conv/pool/etc, stft, window, use_mask, new behavior version 23

- docs/configuration_reference/behavior_version.rst
- returnn/frontend/_backend.py
- returnn/frontend/conv.py
- returnn/tf/frontend_layers/_backend.py
- returnn/tf/layers/basic.py
- returnn/tf/util/basic.py
- returnn/torch/frontend/_backend.py
- returnn/util/basic.py
- tests/test_rf_conv.py
Also, new behavior version 24, or config option `rf_use_consistent_same_padding: bool`.
Fix #1693
> RF PT conv, fix same padding with striding

- returnn/torch/engine.py
After this PR, the torch engine will use `complete_frac` for progress reporting as well as `num_seqs`.
Example line: 
```
ep 1 train, step 23, ctc_8 10.797, ctc_16 10.016, ce 8.758, fer 0.979, grad_norm:p2 85.874, num_seqs 34, max_size:time 239629, max_size:out-spatial 80, mem_usage:cuda:0 60.0GB, 0.926 sec/step, elapsed 0:00:55, exp. remaining 4:59:46, complete 0.31%
```
> PT: also use `complete_frac` for progress reporting

- tests/rf_utils.py
- tests/test_rf_array.py
- tests/test_rf_cond.py
- tests/test_rf_conv.py
- tests/test_rf_loop.py
- tests/test_rf_normalization.py
- tests/test_rf_rec.py
We should have this enabled always. But let's see now what / how much fails.
> RF tests, enable test_single_batch_entry globally

- returnn/datasets/distrib_files.py
- tests/test_Dataset.py
This helps keep the config shorter when the number of files grows large and I vaguely remember Python parsing issues when the (python) files grow too large.
> `DistributeFilesDataset`: allow specifying files via list file

- returnn/frontend/audio/specaugment.py
Before this change, it was impossible to set `max_consecutive_feature_dims=0` because it would be overwritten by the assignment in line 33
> SpecAugment: Fix incorrect `None` checks

- returnn/torch/distributed.py
To provide backend in torch_distributed, we need to get it in this opts check.
> Fix arg check for backend in distributed training

- returnn/torch/distributed.py
In newer Pytorch versions, the default distributed backend dispatching seems to fail on some operations and cause a RuntimeError: No backend type associated with device type cpu (see #1724). We therefore decide to update the default backend value to "cpu:gloo,cuda:nccl" to explicitly force CPU tensors to use gloo and CUDA tensors to use nccl. 
Fix #1724.
> Add new default for torch distributed backend

- .github/workflows/main.yml
Fix #1766.
It's better to explicitly select a version that uses numpy v1 to avoid version conflicts.
> CI: use older espnet version that uses numpy 1
