rwth-i6/returnn

- NetworkRecurrentLayer.py
These cells are tested in 2-dimensional RNNs and some of them yield to much better results. For 1-dimensional RNNs there are no good test - maybe one of you RWTH guys can substitute the LSTMs by these cells and check the performance. Especially for long sequences they maybe outperform the LSTM.
> add cells from paper http://jmlr.org/papers/volume17/14-203/14-203.pdf

- TFNetworkLayer.py
Wrapper around tf.where. To select source depending on some condition.
> Switch Layer

- TFEngine.py
To speed up online translation queries. Behaviour for single sentence unchanged.
> support of batches in single translation query

- GeneratingDataset.py
- SprintDataset.py
new updated pull request (did not want to rewrite the history of my fork on github). other (#58) should be deleted.
> Sprint orth vocab fixed

- LmDataset.py
- MetaDataset.py
Some fixes for the MetaDataset.
I chose to create sequence tags for the MetaDataset by joining the tags of the sub-datasets with "<->", maybe someone has a better idea.
> MetaDataset fixes

- TFNetworkLayer.py
- tests/test_TFNetworkLayer.py
Now the layer converts the input according to the flag auto_use_channel_first
> NCHW support in PoolLayer

- MetaDataset.py
This makes using sequences orderings possible that depend on sequence lengths (`sorted`, `laplace`), without having to pass the sequence lengths from outside (`seq_lens_file`).
> MetaDataset: get seq lengths from data

- tests/test_TFNetworkLayer.py
Training of recurrent networks with shared parameters failed because `base_scope_name` contains "rec/". Maybe it is worth to fix method `base_layer.get_base_absolute_name_scope_prefix()`, but it is used by other parts of returnn.
> Fixed incorrect parameter naming while getting variable names in ReuseParams

- HDFDataset.py
- tests/test_HDFDataset.py
This dataset class implements triplet selection feature for training siamese networks with triplet loss.
> Dataset for Siamese training with triplet loss

- LmDataset.py
Added some functionality to LmDataset:
- Comaptibility with .pkl vocabularies
- LmDataset works with given `seq_list` now
Fixed unknown-replacement for LmDataset.
> Lm dataset fix unk-replacement

- TFNetworkRecLayer.py
- tests/test_TFNetworkRecLayer.py
> Keep track of constraints on layers that are moved out of the RecLayer

- TFEngine.py
- rnn.py
This is needed to output the different factors in Factored NMT (also see #102).
I'm not familiar with all the details of search and if multiple output layers can lead to problems in some cases, but in [my case](https://github.com/patrick-wilken/returnn-examples/tree/master/factored-nmt)  it works and I'm pretty sure it does not break the one-output-layer case.
> Support for multiple output layers

- TFNetworkRecLayer.py
This addresses 
`# TODO check subnet, which extern data keys are used...`
in _SubnetworkRecCell.get_output().
Now, the placeholders for all extern data used in the subnetwork are set. This makes it possible to use all extern data in the layers inside the recurrent unit.
I changed the "x", "y" notation, as we now just loop over the used data keys without distinguishing between the true "y" and additional data.
> SubnetworkRecCell: make all extern data available

- TFNetwork.py
- TFNetworkLayer.py
- TFNetworkRecLayer.py
Added functionality to allow addressing of sub-layers vie "/" separated path. 
This is useful e.g. if you want to share parameters between two recurrent units.
> Get sub layer

- TFNetworkLayer.py
Extend 'var_creation_scope' to include tf.device.
Device can be specified via 'param_device' of LayerBase.
Written by Albert offline at my desk.
> LayerBase, add option to specify device

- NativeOp.cpp
- TFNativeOp.py
> Use blas_gemm_workaround for TF < 1.6, disable 2D-LSTM for TF < 1.6

- TFEngine.py
- TFNetwork.py
- TFNetworkLayer.py
- TFNetworkRecLayer.py
- rnn.py
added options
++eval_output_file_per_seq FILE_NAME  
++loss_name LOSS_NAME 
++output_per_seq_format "seq_tags;seq_len;score;error;pos_score;pos_error"
> Loss out per seq

- TFNetworkLayer.py
- TFUtil.py
- tests/test_TFNetworkLayer.py
If labels has channels first format, transform to channels last
> Loss, NCHW support fixed

- TFNetworkRecLayer.py
get_rec_initial_state_inner class method replaces the previous 'make'
method in get_rec_initial_state.
The new method is more flexible and can be used outside RNNCellLayer
(for example in SelfAttentionLayer).
Include a small change in get_state_by_key, which allows flexible output
shape.
> RNNCellLayer, add get_rec_initial_state_inner method

- TFNetworkRecLayer.py
Adding this primarily to be able to use `SelfAttentionLayer` in step-by-step evaluation graph in C++.
Not fully sure if I have covered other use scenarios related to `initial_state` (e.g., I'm not using `initial_state` in `__init__`): Is there anything else I should have thought about?
> SelfAttentionLayer, add initial_state

- MetaDataset.py
- docs/dataset_reference/combination.rst
- docs/dataset_reference/index.rst
- docs/index.rst
- docs/layer_reference/index.rst
- docs/layer_reference/loss.rst
- docs/layer_reference/shape.rst
- docs/layer_reference/utility.rst
The documentation for the dataset combination was taken from Patrick Wilkens pdf, transformed into markdown.
> Added .gz support for segment files in MetaDataset, Docs update

- MetaDataset.py
- docs/dataset_reference/combination.rst
calling automodule on the classes only returns the docstring without displaying other information, so this is a solution to having docs in the code, but still display it outside the API part.
> moved dataset documentation into code

- TFNetworkLayer.py
With this PR, it becomes possible to perform a max-/min pooling operation only across the time-dimension, while keeping the batch dimension untouched.
For `tf.reduce_max` and `tf.reduce_min`, we can replace all masked values with the minimal/maximal possible value. This way, they won't be selected during max/min operation.
> Support max pooling while keeping the batch dimension

- TFNetworkLayer.py
I propose the following changes to the sampling loss. 
- add support for [fixed_unigram_sampler](https://www.tensorflow.org/api_docs/python/tf/random/fixed_unigram_candidate_sampler). You can specify the respective arguments (distortion, vocab_file or unigram counts, etc.) using the sampler_args dictionary
- explicitly allow to set remove_accidental_hits; Previously this was set to True for both objectives, sampled softmax and NCE. However, for NCE this was not correct as this would correspond to sampled logistic loss (see https://www.tensorflow.org/api_docs/python/tf/nn/nce_loss). See the doc string for additional information.
> sampling_loss: add fixed_unigram sampler, small fix for NCE

- TFNetworkRecLayer.py
Relative positional encoding (Shaw et al., 2018) propose adding a distance term in self-attention instead of using sinusoids after embedding. This PR introduces a relative positional encoding layer that should take the same input as the self-attention layer.
> Implemented relative positional encoding

- TFNetworkRecLayer.py
- tests/test_TFEngine.py
Currently there was no way to use the end layer for stopping decoding without having a choice layer. The test case is modelling a simple sigmoid based end layer, which is similar to the network needed for TTS.
> enable end layer usage without a choice layer

- GeneratingDataset.py
I added 2 new feature extraction methods, one for linear spectrograms and a modified version of log-mel-spectrograms with additional options and a different scaling. 
Other additions are:
- The peak normalization can be disabled now
- A preemphasis filter can be set
- The features can be stacked as "superframes" (https://arxiv.org/pdf/1507.06947.pdf, section 2.3, https://arxiv.org/abs/1703.10135)
- the normalization can be a single value instead of a file or numpy array representing each feature dimension
The superframes can in theory be implemented as a layer, but with the existing layers I was not able to produce this behavior, and additional layers for conversion would slightly increase the memory load.
> added additional audio options for feature extraction

- HDFDataset.py
- tests/test_HDFDataset.py
I assume there is a good reason why the files were closed and re-opened, but closing and re-opening to get each tag felt wrong.
I added (and enabled) a test that failed and is fixed by the first commit. I hope enabling the test doesn't cause the next round of trouble ':D
> HDFDataset tag fix

- tools/bliss-to-ogg-zip.py
If a sprint feature cache is given, the generated ogg files are synchronized to the feature caches to overcome possible mismatches, e.g. by dc-detection.
> Feature cache synchronization for bliss-to-ogg-zip tool

- HDFDataset.py
- TFNetwork.py
- docs/configuration_reference/debugging.rst
- docs/configuration_reference/generation_search.rst
I wrote some small commits that I did not want to push directly into the master branch without review. I thought it is easier to bundle it in a single pull request.
> Collection of small changes

- TFNetworkLayer.py
- tests/test_TFNetworkLayer.py
Hi,
this PR adds a test for the `SoftmaxOverSpatial` layer in the case of window masking.
Previously this functionality was broken due to some previous changes in the "default" case.
Some of the changes were already in some branch, but got lost I think.
Also, see
```python
indices.set_shape((None, None))  # required for older TF versions
```
which is a workaround for an error I got for TF 1.4.1, where the tensor shape could not get inferred automatically (and thus `nd_indices` failed). Hope this is ok.
The test is also good to verify various edge cases for the masking.
Cheers
> Fix softmax window masking

- TFEngine.py
- tests/test_TFEngine.py
Hi,
this PR aims to fix the `debug_grad_summaries` config-option.
Currently it does not add any summaries to the event file.
This is due to the order of the operations `engine.network.get_fetches_dict` and `engine.updater.get_optim_op`.
To test this, I had to add an option to provide a `callable` (so a lambda or so) to the `extra_fetches` parameter of the `Runner` class, so that the operation which gets the summary-tensor is called once it is actually created.
This may lead to issues later, maybe we have to implement this more generic (e.g. it breaks if `Data` becomes callable). But maybe this is enough.
Also the actual fix is a bit ugly, maybe you have a better suggestion?
Cheers,
André
> Fix debug_grad_summaries

- TFNetworkLayer.py
`get_concat_sources_data_template` should be the right thing to do in all cases to create the output template.
Logic depending on `n_out` can lead to problems, e.g.:
`n_out` is set via `LayerBase.transform_config_dict()` if a layer has a target. Using super(CopyLayer, cls).get_out_data_from_opts in this case fails to set `sparse=True`.
Should we add a check that, if `out_type` or `n_out` are given, they match the result of  `get_concat_sources_data_template`?
> CopyLayer: always get out_type from sources if possible

- Dataset.py
I added a way to explicitly specify left and right context for the `context_window` in `Dataset.py`. To do that, `context_window` should be a dict with the keys "left" and "right".
There some code in `TFDataPipeline.py` in `TFChunkingQueueRunner` which also uses a context window but not exactly in the same way as done in `Dataset.py`. Not sure if that should be updated, too...
> Dataset: Allow explicit left/right context window

- Dataset.py
sort_bin_shuffle first sorts sequences by length, creates bins, and
shuffles the bins.
sort_bin_shuffle_x2 does an extra shuffling within each bin after
sort_bin_shuffle.
> Dataset, add sort_bin_shuffle and sort_bin_shuffle_x2 seq ordering

- TFNetworkRecLayer.py
- tests/test_TFEngine.py
This fixes  #225
Two things to discuss:
1. Resolving beams in `body()` is now pretty inconsistent (`translate_to_this_search_beam`, `SelectSearchSourcesLayer.transform_func` and `select_src_beams`). I think we should refactor the code, such that there is one utility function, which translates beams taking a sequence of search choices, and `SelectSearchSourcesLayer` should use this function.
2. It is a bit vague how exactly the latest search choice in the recurrent unit should be determined. I now calculate it globally, comparing all search choices of `needed_outputs`. Is there any downside to this? It should give the same result as the first "prev" layer in the choice sequence and it should be enough to do it only once, but there is simply no obvious layer to start the choice sequence …
> SubnetworkRecCell: resolve beams of seq_len

- HDFDataset.py
> Ensure partition_epoch = 1 for cache_size > 0

- TFNetworkLayer.py
- tests/test_TFNetworkLayer.py
A time mask is applied to take different sequence lengths into account, the elements are divided by the sequence length and then tf.reduce_sum is applied. Flattening is removed.
> ReduceLayer, allow reduce_mean of time dimension without flattening

- .travis.yml
- NativeOp.cpp
- TFKenLM.py
- TFNativeOp.py
- TFOpenFst.py
- TFUtil.py
- tests/test_TFEngine.py
- tests/test_TFUtil.py
> TF 1.15 compatibility

- GeneratingDataset.py
the librosa function _rmse_ was renamed for librosa version 0.7 to _rms_
> add version check for librosa func rms(e)

- .travis.yml
- LmDataset.py
- tests/test_TranslationDataset.py
- tools/hdf_dump_translation_dataset.py
Alternative to #249
Support for translation factors now in a derived dataset. 
Nevertheless, I needed to change TranslationDataset quite a lot to be able to reuse the code in the derived class. But I don't think I made the code worse :)
Also, finally added tests.
For most factors we don't want an unknown class, so I made it configurable per data key.
The last commit is related because the hack to use the source file as target in case you don't have the target no longer works in case of factors, because the number of factors can be different. Note, that "source_only" is different, as we still want to register the target data key, just don't feed values.
> TranslationFactorsDataset

- TFNetworkLayer.py
I added a `DctLayer` which wraps `tf.signal.dct`. So far, that's all it does, so no specific handling of axes is done. `tf.signal.dct` always computes the DCT over the last dimension.
> TFNetworkLayer: add DctLayer

- MetaDataset.py
Last feature from our "MT branch"...
This adds a straight-forward way to control the effective sizes of the sub-datasets. Useful to bias or not bias the model towards one type of data. An alternative would be to use certain combinations of partition/repeat epoch, however this setting depends on the dataset sizes and only allows simple integer fractions.
Configuration in the CombinedDataset dict would look something like this:
`"sampling_sizes": {"sub_dataset_1": 10, "sub_dataset_2": 50, "sub_dataset_3": 100}`
Meaning in each epoch, 10 sequence are taken from sub_dataset_1, 50 from sub_dataset_2 and 100 from sub_dataset_3. Sequences are taken in order, therefore all sequences from one subdatasets are seen the same number of times.
> CombinedDataset: sampling from sub-datasests

- GeneratingDataset.py
Allow using multiple channels for raw audio in `ExtractAudioFeatures` and therefore in `OggZipDataset`. If `num_channels` is set, the data will be of shape `(T, num_channels, num_feature_filters)`, otherwise just `(T, num_feature_filters)` as before.
> ExtractAudioFeatures: enable multichannel raw audio

- returnn/tf/layers/basic.py
I currently need weighting of positive vs. negative labels when doing a binary decision. Probably a nice to have.
> BinaryCrossEntropyLoss: added weight for positive labels

- returnn/tf/layers/rec.py
Related to Issue #327 
Note that this does not add new test cases.
> FIXED: RelativePositionalEncodingLayer wrong dim in output Data

- tools/bliss-to-ogg-zip.py
For some reason the FFMPEG calls had very faulty results (mostly missing 3/4 of the audio content) when the input was already in .ogg format, and the file duration was already correct. I was not able to find the source of the error, so for me the safest solution was to add the same option (not doing any conversion or as I already had in my old custom Job for creating ogg-zip-files.
An alternative would be to create a separate job, that would just pass through the audio and also support different formats than .ogg (because the OggZipDataset supports basically all formats of the soundfile/libsndfile library).
This is open for discussion.
> Added no-conversion option in bliss-to-ogg-zip.py

- tests/test_TFNetworkRecLayer.py
> ADDED: proper test case for RelativePositionalEncodingLayer

- returnn/tf/layers/basic.py
I found the docstring for CompareLayer not very clear, so I added some details.
> Added details to the doc of CompareLayer

- docs/index.rst
- docs/internals/search.rst
This is documentation code that was written by @patrick-wilken for internal usage. I am not sure if everything is correct, because I lack the knowledge myself, but maybe someone can point out issues or confirm correctness.
> docs: add internal search description text

- returnn/tf/hyper_param_tuning.py
This small edit fixes the error in #345 by assigning the "training" task to each run's config.
> Fixing demos/demo-hyper-param-tuning.config

- returnn/tf/layers/signal_processing.py
- tests/lint_common.py
Fix code style issues in `signal_processing.py`. Mainly long lines, variables with uppercase etc. Also usages of `tf.contrib` are changed for TF 2 compatibility.
> signal_processing.py: fix code style issues

- returnn/tf/layers/basic.py
See some last discussion in #354.
> PostfixInTime: Fix template generation, dependencies

- returnn/tf/layers/basic.py
tf.ceil might return tf.float64
> minor fix for slice layer

- returnn/tf/layers/basic.py
I added a class `NormLayer` which normalizes over specified axes, e.g. time and/or feature axis.
> Added NormLayer class

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
Pretty straight forward extension of existing DotLayer code. Comes with a test case for the new behavior.
> Generalize DotLayer to support inputs without a batch-dim

- returnn/tf/layers/rec.py
- returnn/tf/util/data.py
- tests/test_TFNetworkRecLayer.py
This fixes the problems described in #380 and additional problem in the template output of the `SwapAxesLayer` when swapping the feature axis away from the last position.
> Fix SwapAxesLayer and [B,F,T] input for RecLayer

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
This is my implementation of a wrapper around `tf.gather`. Sorry @albertz, I kind of completely missed that you started work on this in c968dd97bf57add1aeaafb6d0326a05939c7a9eb, so I essentially built this layer from scratch.
This implementation here however supports `position` to be any other layer and thus much more flexible (also much more complicated though..). I added a special case in `transform_config_dict` that handles the case that `position` is an int by "wrapping" it in a `ConstantLayer`. We can in the future easily adapt this to also support more complex constants like entire arrays.
> GatherLayer: Position can be any layer now

- returnn/tf/layers/base.py
Allows for {beta,gamma}-initialization for `batch_norm`.
As written in [Accurate, Large Minibatch SGD:Training ImageNet in 1 Hour](https://arxiv.org/pdf/1706.02677.pdf),
initializing the `gamma` (scale) parameter to zero for the last layer of each residual block may improve initial convergence.
> For BN layers, the learnable scaling coefficient γ is initialized to be 1, except for each residual block’s last BN where γ is initialized to be 0.
> Setting γ= 0 in the last BN of each residual block causes the forward/backward signal initially to propagate through the identity shortcut of ResNets, which we found to ease optimization at the start of training.
> This  initialization improves all models but is particularly helpful for large minibatch training as we will show.
Also, …
> Initialization for batchnorm gamma/beta

- docs/configuration_reference/optimizer_settings.rst
- returnn/tf/updater.py
Includes the Noam-style scheduluing example from "Attention is all you need"
> User-defined step-wise learning rate function

- returnn/datasets/map.py
This is @JackTemaki 's implementation as discussed in #353.
I've now split it into a general and a RETURNN Dataset specific part and changed a few minor things.
Is the goal that giving a list to MapDatasetWrapper should work? How would we handle `get_seq_tag()` in this case? Also exception handling for the other methods which are not part of the `list` API would have to be adjusted (e.g. catching AttributeError).
> Map-style dataset base for user-side datasets

- returnn/tf/layers/basic.py
- returnn/tf/util/data.py
- tests/test_TFUtil.py
> Rewrite Data.copy_compatible_to, adds test cases & fixes for #428

- returnn/tf/layers/basic.py
This was missing in my previous PR #426.
> SwitchLayer: Fix get_dep_layers for constant inputs

- tests/test_TFNetworkLayer.py
> SplitLayer: Test beam search

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
This was broken in fe4a0a4da832893b0b4f0bb6d233834ad3f0e9dd.
> MergeDimsLayer: Fix size_placeholder in get_out_data_from_opts

- returnn/tf/layers/basic.py
I needed attention over encoder positions from 0 to `n(t)`, where `n` is determined by the network in each decoder step `t`.
Using `window_start` and `window_size` of `SoftmaxOverSpatialLayer` is the best way to do this, right? I have a layer calculating `n`, I just need to set `window_start` to 0 which is now possible (without creating a ConstantLayer or similar).
What is the difference between `start` and `window_start` by the way? They seem to do the same thing.
> SoftmaxOverSpatialLayer: support integers as window start

- returnn/import_/common.py
Adds another env-var to be able to specify the _pkg_import_path from outside.
> import_ add import path env var

- returnn/tf/layers/base.py
- returnn/tf/layers/basic.py
- returnn/tf/layers/rec.py
- returnn/tf/network.py
- returnn/tf/util/data.py
- tests/test_TFNetworkLayer.py
- tests/test_TFUtil.py
- tools/compile_tf_graph.py
> Packed arrays, next round

- returnn/tf/layers/base.py
- returnn/tf/layers/rec.py
- returnn/tf/network.py
(I would push this directly to master, but just want to see the tests passing... No need for review.)
> Random stuff

- returnn/tf/layers/basic.py
Fixes output dim if no feature dim.
Fixes that placeholder shape is consistent with output shape if axis is static.
> RangeInAxisLayer: Small fixes

- docs/getting_started/tech_overview.rst
> Added tasks documentation

- returnn/tf/util/basic.py
- tests/test_TFNetworkRecLayer.py
This caused problems with `SelfAttentionLayer` inside `MaskedComputationLayer`.
> Fix for select_src_beams for empty tensor

- returnn/tf/layers/basic.py
If the feature dim changed somehow, we need to reset the output dim to be consistent.
> MergeDimsLayer: Set output dim

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
This PR extends `RepeatLayer` s.t. it also works if the input values / repetition count tensor do not have a batch dim.
Also, if the repetition count tensor does not have the axis we repeat along, it is simply broadcasted along the entire axis.
This allows you to now just give a single int as `repetitions` input.
> RepeatLayer: Support input without batch dim, constant int repetitions

- tests/test_TFNetworkRecLayer.py
> Test case for #500

- returnn/tf/layers/basic.py
- returnn/tf/util/data.py
- tests/test_TFNetworkLayer.py
Basically wraps around [tf.searchsorted](https://www.tensorflow.org/api_docs/python/tf/searchsorted).
The functionality should be done, and it's working in my own config as far as I can tell.
I still want to add some unit test, then I'll remove the draft status.
> Add SearchSortedLayer

- docs/configuration_reference/behavior_version.rst
- docs/configuration_reference/index.rst
- returnn/__main__.py
- returnn/log.py
- returnn/tf/engine.py
- returnn/tf/layers/base.py
- returnn/util/__init__.py
- returnn/util/basic.py
Also adds the first behavior_change by introducing: #519.
> Introduce behavior_version parameter

- returnn/tf/layers/base.py
- returnn/tf/layers/basic.py
- returnn/tf/util/basic.py
- tests/test_TFNetworkLayer.py
Pads the input tensor using replication of the input boundary.  
One-dimensional case has been implemented so far.
> add replication mode for PadLayer

- returnn/tf/layers/base.py
- returnn/tf/layers/basic.py
- returnn/tf/layers/rec.py
- returnn/tf/network.py
Related:
https://github.com/rwth-i6/returnn_common/pull/8
> allow layers directly for target option

- returnn/tf/layers/rec.py
- returnn/tf/util/data.py
> RecLayer, support for predefined time-dim-tag

- returnn/datasets/hdf.py
Workaround for known overhead when accessing h5py.File objects.
See #498 and https://github.com/h5py/h5py/issues/994#issuecomment-364767614.
> HDFDataset: cache h5py.Dataset objects for efficiency

- returnn/datasets/basic.py
- returnn/datasets/cached.py
- returnn/datasets/hdf.py
- returnn/theano/engine_util.py
Some cleanups for the Dataset base class.
> Dataset attributes cleanup

- demos/demo-returnn-as-framework.py
- returnn/__main__.py
- returnn/config.py
- returnn/log.py
- returnn/tf/engine.py
- returnn/tf/layers/basic.py
- returnn/tf/layers/rec.py
- returnn/tf/util/data.py
- returnn/util/basic.py
- tests/_setup_test_env.py
- tests/test_TFEngine.py
- tests/test_TFNetworkLayer.py
- tests/test_TFNetworkRecLayer.py
- tests/test_TFNetworkSigProcLayer.py
- tests/test_TFUpdater.py
> Dim tag more

- returnn/tf/layers/basic.py
> RangeInAxisLayer, keepdims unsupported, not needed

- returnn/tf/network.py
- tests/test_TFNetworkLayer.py
Starting draft to fix #580 
Introduced a test, which should be working at the end. Starting to debug now. Any suggestions / feedback on what might cause the issue appreciated.
> unused subnetwork output fix

- returnn/tf/layers/rec.py
- tests/test_TFNetworkRecLayer.py
As mentioned in a comment in #637
> Rec subnet exception handling, less verbose

- returnn/tf/layers/rec.py
Small fix for small issue in #635
> Rec subnet, output accumulated layer, use in loop Data template

- returnn/datasets/meta.py
This annoyed me for a long time now, and now I had a case again where this crashed, so I tried to fix it.
> allow MetaDataset without 'data' key

- returnn/tf/layers/rec.py
> Rec subnet construct accum output layer, better dim tag

- returnn/tf/layers/basic.py
- returnn/tf/util/basic.py
- returnn/tf/util/data.py
- returnn/util/basic.py
- tests/test_TFNetworkLayer.py
> MergeDimsLayer, support dyn size ext, fix #662

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
> SplitDimsLayer, fix feature_dim_axis for batch-feature-major input

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
> TransposedConvLayer, keep dim tags when unchanged

- returnn/tf/layers/basic.py
> cleanup AllophoneStateIdxParserLayer

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
> PadLayer, fix dim tag for no-op

- returnn/tf/layers/base.py
- returnn/tf/layers/rec.py
- tests/test_TFNetworkRecLayer.py
> Rec subnet, use WrappedInternalLayer for opt

- docs/advanced/profiling.rst
- returnn/tf/engine.py
Adds an option `store_tf_profile` to record data for the [TF profiler here](https://www.tensorflow.org/guide/profiler#profiler_tools).
I found this extremely useful.
> Profiling with the TF profiler

- returnn/tf/network.py
- tests/test_TFNetworkRecLayer.py
> Fix prev in Rec subnet

- returnn/tf/util/basic.py
This is related to #694.
@albertz
> Explicitly execute function on CPU

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
> GatherLayer: fix batch.beam error

- returnn/tf/layers/base.py
- returnn/tf/layers/basic.py
- returnn/tf/layers/rec.py
- returnn/tf/network.py
- returnn/tf/util/basic.py
- tests/test_TFNetworkLayer.py
- tools/compile_tf_graph.py
Also for https://github.com/rwth-i6/returnn_common/issues/25.
> layer name_scope option

- returnn/sprint/error_signals.py
- returnn/tf/layers/basic.py
Some small fixes to make the `fast_bw` loss layer usable for RASR-loss dependent CTC training.
> fix fast bw loss

- returnn/tf/layers/base.py
> Layer state option, for any recurrent layers

- docs/configuration_reference/behavior_version.rst
- returnn/tf/layers/basic.py
- returnn/tf/layers/rec.py
- returnn/tf/util/data.py
- returnn/util/basic.py
- tests/test_TFEngine.py
- tests/test_TFNetworkLayer.py
- tests/test_TFNetworkRecLayer.py
- tools/import-t2t-mt-model.py
> DotLayer, no int axes, changed defaults

- returnn/tf/layers/basic.py
- returnn/tf/util/data.py
- tests/test_TFNetworkLayer.py
> ConcatLayer

- returnn/tf/layers/rec.py
- tests/test_TFNetworkRecLayer.py
> RecUnstackLayer, declare_rec_time option, axis optional

- returnn/tf/layers/base.py
- returnn/tf/layers/rec.py
- returnn/tf/network.py
- tests/test_TFNetworkRecLayer.py
> RecLastOutputLayer, way to get rec last layer output

- returnn/tf/layers/base.py
- returnn/tf/layers/basic.py
- returnn/tf/layers/rec.py
- returnn/tf/util/data.py
> Data.sparse_dim, DimensionTag.vocab

- returnn/tf/layers/base.py
- returnn/tf/layers/rec.py
- returnn/tf/network.py
- returnn/tf/util/data.py
- tests/test_TFNetworkLayer.py
> Layer out_shape option for verification

- docs/configuration_reference/behavior_version.rst
- returnn/tf/layers/base.py
- returnn/tf/layers/basic.py
- returnn/tf/layers/rec.py
- returnn/tf/util/basic.py
- returnn/tf/util/data.py
- returnn/util/basic.py
- tests/test_TFNetworkLayer.py
- tests/test_TFNetworkRecLayer.py
- tests/test_TFUtil.py
> allow_broadcast_all_sources, changed default, new behavior version

- returnn/tf/layers/rec.py
- tests/test_TFNetworkRecLayer.py
Note that this might break configs using this layer but we expect this to be rare at this point.
This is consistent to the discussion in #597.
> CumConcatLayer, out_spatial_dim instead of new_dim option

- returnn/tf/layers/basic.py
- tests/test_TFNetworkRecLayer.py
> SplitLayer out_dims option

- returnn/tf/layers/basic.py
- returnn/tf/util/data.py
Implement some of the suggestions from #597.
> Explicit output dim tags for RandIntLayer, VariableLayer, ConstantLayer

- returnn/tf/updater.py
- tests/test_TFEngine.py
The behavior is slightly different to the Keras Nadam optimizer.
Fix #766.
https://github.com/tensorflow/tensorflow/issues/53204
> NadamOptimizer using the native kernel

- returnn/tf/layers/basic.py
> ScatterNdLayer, out_spatial_dim option

- returnn/tf/layers/basic.py
> SliceNdLayer, size can be DimensionTag

- returnn/tf/layers/basic.py
> SliceLayer, out_dim option

- docs/configuration_reference/behavior_version.rst
- returnn/tf/layers/basic.py
- returnn/tf/util/data.py
- returnn/util/basic.py
- tests/test_TFNetworkLayer.py
- tests/test_TFNetworkRecLayer.py
Same for get_axis_from_description.
Fix #773.
This introduces a new behavior version (#508).
> Data.get_axes_from_description, change default allow_int

- returnn/tf/layers/basic.py
> PadLayer, out_spatial_dims option

- returnn/tf/layers/basic.py
#597
This is more consistent because the new output dim(s) could also be a feature dim.
> PadLayer, rename out_spatial_dims to out_dims

- returnn/tf/layers/basic.py
> MergeDimsLayer, handle out_dim option

- returnn/tf/layers/basic.py
> SplitDimsLayer, dims can be list of DimensionTag

- returnn/tf/layers/basic.py
- tests/test_TFNetworkRecLayer.py
> ConvLayer fix moved out of rec loop without specified dim tags

- returnn/tf/layers/basic.py
- tests/test_TFNetworkRecLayer.py
Similar to #789.
Also fix for `TransposedConvLayer` for #573.
Also same for #594.
> TransposedConvLayer in_dim, out_dim, in_spatial_dims, out_spatial_dims

- returnn/tf/layers/basic.py
- returnn/tf/util/basic.py
- tests/test_TFNetworkRecLayer.py
> WindowLayer/CumsumLayer: Extend check for when recurrent

- returnn/tf/layers/basic.py
> ResizeLayer out_dim option

- returnn/tf/layers/basic.py
> PrefixInTimeLayer, PostfixInTimeLayer, axis and out_dim options

- returnn/tf/layers/basic.py
> UnflattenNdLayer, in_dim, out_dims options

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
> CompareLayer: set allow_broadcast_all_sources when calling Data.get_common_data

- returnn/tf/layers/basic.py
- returnn/tf/native_op.py
> TimeChunkingLayer axis option, TimeUnChunkingLayer, dim tags

- returnn/tf/layers/basic.py
> ReduceOutLayer, handle out_dim

- returnn/tf/layers/basic.py
> StackLayer, out_spatial_dim option

- returnn/tf/layers/rec.py
> EditDistanceTableLayer, handle out_dim

- returnn/tf/layers/basic.py
> TileLayer, out_dims option

- returnn/tf/layers/rec.py
- tests/test_TFNetworkRecLayer.py
> RecLayer, check for NativeLSTM (v1) broken initial_state usage, change default LSTM

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
> SwitchLayer: remove sanity check from get_out_data_from_opts

- returnn/tf/util/data.py
- tests/test_TFNetworkLayer.py
> Fix consistent dim tags after beam assignment

- returnn/tf/layers/base.py
- returnn/tf/layers/basic.py
- returnn/tf/layers/rec.py
- returnn/tf/layers/signal_processing.py
- returnn/tf/network.py
- returnn/tf/util/basic.py
- returnn/tf/util/data.py
- tests/test_TFEngine.py
- tests/test_TFNetworkLayer.py
- tests/test_TFNetworkRecLayer.py
- tests/test_TFUtil.py
- tools/compile_tf_graph.py
> simplify dim tag user API

- returnn/tf/layers/base.py
- tests/test_TFEngine.py
- tests/test_TFNetworkLayer.py
> ReuseParams via layer output

- returnn/__main__.py
- returnn/datasets/basic.py
Make it possible to define a custom dataset object in the returnn config.
> Dataset, make it possible to use a custom dataset object in the config

- returnn/tf/layers/basic.py
> SliceNdLayer, out_spatial_dim option

- returnn/tf/layers/basic.py
> MathNormLayer, axis option

- returnn/tf/layers/basic.py
> NormLayer, param_shape support dim tags

- docs/configuration_reference/behavior_version.rst
- returnn/tf/layers/basic.py
- returnn/util/basic.py
Fix #787.
Introduces new behavior version (#508).
> ConvLayer, with_bias=True by default

- returnn/tf/layers/basic.py
> LayerNormLayer, handle in_dim, out_dim

- returnn/native_op.cpp
- returnn/tf/layers/base.py
- returnn/tf/layers/rec.py
- returnn/tf/native_op.py
- returnn/tf/network.py
- returnn/tf/util/data.py
- tests/test_TFNetworkRecLayer.py
Also implement the corresponding support for RecLayer.
(Partially) fix #847.
(Partially because the corresponding support is missing for other layers but this can be done in follow-up PRs.)
> single_step_dim special dim tag marker

- returnn/tf/layers/basic.py
- returnn/tf/util/data.py
this is relevant for the dropout_noise_shape option
> extend get_bc_shape

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
> ReinterpretDataLayer: set dyn_size in the correct order

- returnn/tf/layers/basic.py
- tests/test_TFNetworkRecLayer.py
> DotLayer, allow auto-infer of var1/var2

- returnn/tf/layers/rec.py
- tests/test_TFNetworkRecLayer.py
> SplitBatchBeamLayer

- returnn/tf/util/data.py
- tests/test_TFUtil.py
> Dim __copy__ and __deepcopy__ 

- returnn/tf/layers/basic.py
Some cleanups for GatherLayer.
> GatherLayer, cleanup matching dims logic

- returnn/tf/layers/basic.py
- returnn/tf/util/data.py
Partly taken from #871, just to separate this.
> DotLayer and Data Dim match, small improvements

- returnn/tf/layers/base.py
Draft to check if the code for target dependency resolve can be simplified.
> remove eval check in transform_config_dict

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
> DotLayer, support sparse input

- tools/calculate-word-error-rate.py
I have some jobs that write all hypothesis into the output file, but the WER tool should also work in that case.
> nbest-list acceptance for WER tool

- docs/configuration_reference/behavior_version.rst
- returnn/tf/layers/base.py
- returnn/util/basic.py
- tests/test_TFNetworkLayer.py
Fix #522
This introduces a new behavior version (#508).
> batch norm, new defaults

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
Fix #908.
Follow-up to #845.
Related: https://github.com/rwth-i6/pytorch-to-returnn/pull/78
> Fix issues in SplitDimsLayer

- returnn/tf/layers/base.py
- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
For contrastive losses.
@mmz33 @vieting
> Random indices

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
Also needed for: https://github.com/rwth-i6/pytorch-to-returnn/pull/85
> SplitDimsLayer, fix split batch dim

- returnn/tf/layers/basic.py
- returnn/tf/util/data.py
- tests/test_TFNetworkLayer.py
> ReinterpretDataLayer, allow resetting batch dim

- returnn/tf/layers/basic.py
> RandIntLayer, fix for dynamic dim tags

- returnn/tf/layers/basic.py
> ExpandDimsLayer, support dim tag

- returnn/tf/layers/basic.py
> ReinterpretDataLayer, batch_dim_base option

- returnn/tf/network.py
> debug_print_layer_output option

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
> LengthLayer, fix for batch

- tests/test_TFNetworkLayer.py
> Contrastive loss demo

- returnn/datasets/sprint.py
> fix num_outputs for speaker_name

- returnn/tf/layers/basic.py
- returnn/tf/util/data.py
- tests/test_TFNetworkLayer.py
Via rwth-i6/pytorch-to-returnn#100
> Fixes for setting dim tag on dyn batch dim tensor

- returnn/datasets/audio.py
- returnn/datasets/basic.py
- returnn/datasets/sprint.py
- returnn/sprint/interface.py
- returnn/tf/engine.py
- returnn/tf/layers/basic.py
- returnn/tf/layers/rec.py
- returnn/tf/network.py
- returnn/tf/util/basic.py
- tests/pycharm-inspect.py
https://github.com/rwth-i6/returnn/pull/930#discussion_r797587361
> PyCharm inspect, check indentation

- returnn/tf/layers/basic.py
For https://github.com/rwth-i6/returnn_common/issues/18.
> TrainFlagLayer

- returnn/datasets/cached.py
Fixup for 39d5c6f.
@mattiadg, can you check whether this works for you?
> CachedDataset: fixed check whether sequence order changed

- returnn/tf/layers/basic.py
Allow `kind="floordiv"` in `CombineLayer`.
> CombineLayer: add floordiv

- returnn/tf/layers/base.py
- returnn/tf/layers/basic.py
- returnn/tf/layers/rec.py
> Loss._flatten_or_merge cleanup

- returnn/tf/util/basic.py
> flatten_with_seq_len_mask cache

- returnn/tf/network.py
- tests/test_TFNetworkLayer.py
A (frame-wise) computation like `loss_per_frame = CE(softmax(y), targets)` would in the end only consider the non-padded frames for `loss = sum(loss_per_frame)`. Let's assume `loss_per_frame` is of shape [B,T]. This can be achieved in multiple ways:
* The `sum` could apply masking (like our `ReduceLayer`).
* We could flatten `loss_per_frame`, i.e. take only the non-padded frames, i.e. of shape [B'] where B' <= B*T.
* The flattening can be pushed upwards through the computation. We could already flatten `y` and `targets` instead. This would be more efficient, as we don't waste computation on softmax. But it can be further pushed upwards. E.g. `y` is likely the result of a matmul. The flattening can happen before that. Etc.
This PR adds code which automatically pushes the flattening upwards …
> Auto-flatten optimization

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
> TransposedConvLayer fix time major input

- returnn/tf/util/data.py
- tests/test_TFUtil.py
> Data find_matching_dim_map better logic

- returnn/tf/compat.py
- returnn/tf/layers/basic.py
- returnn/tf/layers/rec.py
- returnn/tf/network.py
- returnn/tf/util/basic.py
- returnn/tf/util/data.py
- tests/test_TFUtil.py
This is an updated version of #700.
Might fix #962.
Related:
https://github.com/tensorflow/tensorflow/issues/32106
> TF2, control flow v2 support

- returnn/tf/layers/basic.py
- returnn/tf/util/data.py
- tests/test_TFUtil.py
> ConvLayer, define out dims already in get_out_data_from_opts

- returnn/datasets/util/feature_extraction.py
Fix #969.
as discussed in #969 here is a pr to make returnn compatible with the latest version of librosa.
All changes _should be_ backwards compatible based on the librosa documentation.
> add support for librosa v0.9.1

- returnn/tf/layers/rec.py
- tests/test_TFNetworkRecLayer.py
> MaskedComputationLayer name_scope logic

- returnn/tf/layers/signal_processing.py
- tests/test_TFNetworkLayer.py
Add `IstftLayer` similar to `StftLayer` in #994.
> add IstftLayer

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
I created the test for #998 but then I realized that the reported bug is invalid.
However, I noticed that there is some inconsistency in the `time_dim_axis` of the output, so I fixed that here.
> ConvLayer (and co) out data, fix time_dim_axis

- returnn/tf/layers/base.py
- returnn/tf/layers/basic.py
- returnn/tf/layers/rec.py
- returnn/tf/network.py
- tests/test_TFNetworkLayer.py
- tools/compile_tf_graph.py
Fix #993.
At the same time, this probably is a good preparation to simplify a flat net construction implementation (#992).
> Cleanup subnet construction, more shallow stack

- returnn/tf/layers/rec.py
- tests/test_TFNetworkRecLayer.py
> MaskedComputationLayer, fix dyn_size with beam

- returnn/tf/network.py
- tests/test_TFNetworkLayer.py
> TFNetwork construct_layer, small fix

- returnn/tf/layers/signal_processing.py
Allow using `in_spatial_dims`, `out_spatial_dims` and `out_dim` in `StftLayer` and `IstftLayer`. It's just passed on to the underlying logic defined by the `ConvLayer`/`TransposedConvLayer`.
> (I)StftLayer dim tag changes

- tests/test_tools.py
- tools/compile_tf_graph.py
> compile TF graph, fix parent dim tag usage

- returnn/tf/layers/basic.py
- returnn/tf/layers/rec.py
- returnn/tf/network.py
- tests/test_TFNetworkRecLayer.py
> Rec subnet, internal debug template layer, small fix

- returnn/tf/layers/basic.py
- returnn/tf/layers/rec.py
> RecLayer fix some fixed seq len handling

- .github/workflows/main.yml
> CI, use pytest

- returnn/tf/layers/basic.py
- returnn/tf/util/data.py
> ReduceLayer, fix for custom seq len shape

- returnn/tf/util/data.py
- tests/test_TFEngine.py
Actually mostly just a test case. It seems to work already.
Only a small minor fix was needed.
> Static batch dim support

- returnn/tf/util/data.py
- tests/test_TFNetworkLayer.py
cf. #1057 
There probably is a different location to fix this, but I think its a good starting point for a discussion on how to fix this.
> Fix adding batch dim

- returnn/datasets/sprint.py
- returnn/sprint/error_signals.py
- returnn/util/basic.py
> close_all_fds_except

- returnn/tf/layers/basic.py
- returnn/tf/util/data.py
Fix #1054.
Fix https://github.com/rwth-i6/pytorch-to-returnn/issues/124.
> Fix dim tag derived_from_tag cycle

- returnn/tf/layers/rec.py
- tests/test_TFNetworkRecLayer.py
Triggered via (but otherwise unrelated): https://github.com/rwth-i6/returnn_common/pull/160
> RecLayer subnet access last, fix for scalar time dim

- returnn/tf/network.py
- returnn/tf/util/data.py
- tests/test_TFUtil.py
Follow-up to #1067.
Should fix https://github.com/rwth-i6/returnn/issues/1069.
> Batch info handling fixes

- returnn/util/basic.py
- tests/test_Util.py
Fix #1070
Also nicer reporting.
> dict_diff_str, fix for non-str keys

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
See discussion here: https://github.com/rwth-i6/returnn_common/pull/194
> TransposedConvLayer, support reuse of out_spatial_dims

- returnn/datasets/util/feature_extraction.py
Adds librosa pitch extraction as option for feature extraction.
> Pitch extraction

- returnn/datasets/util/feature_extraction.py
`db_mel_features` already have that, but I need this also for linear features now.
> add center flag to linear and mfcc features

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
> RangeInAxisLayer more generic

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
Extension for #1096.
Like the `RangeInAxisLayer` change from #1100.
> LengthLayer more generic

- returnn/tf/layers/basic.py
Two important changes:
* log_softmax(logits) instead of log(softmax(logits)). Much more stable.
* Correct masking of gradient. Filters away inf/nan in the padded area.
Note that this just follows what `returnn.tf.native_op.ctc_loss` is already doing.
> FastBaumWelchLoss, more stable

- returnn/tf/layers/rec.py
This came up via https://github.com/rwth-i6/returnn_common/issues/199.
> RecLastOutputLayer, resolve indirect layers

- returnn/tf/layers/basic.py
This came up via https://github.com/rwth-i6/returnn_common/issues/199.
> TopKLayer, fix undefined k_dim

- returnn/tf/layers/base.py
- returnn/tf/network.py
- returnn/tf/util/data.py
This came up via https://github.com/rwth-i6/returnn_common/issues/199.
> Layer output, always set batch info

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
> Dim tag declare_same_as fix

- returnn/native_op.py
A minor fix to prevent crashes.
> FastBaumWelchOp debug functions, small fix

- returnn/tf/util/data.py
Via https://github.com/rwth-i6/returnn_common/issues/200.
Somewhat this is also a reminder for #975...
> Dim, set batch if not set

- returnn/tf/network.py
Via https://github.com/rwth-i6/returnn_common/issues/200.
> ExternData batch_info fix

- returnn/tf/util/data.py
Via https://github.com/rwth-i6/returnn_common/issues/200.
> Dim declare_same_as, prioritize explicit defined

- returnn/datasets/meta.py
- returnn/datasets/util/vocabulary.py
- returnn/tf/engine.py
- returnn/theano/engine.py
- returnn/theano/engine_task.py
- tests/test_GeneratingDataset.py
The refactor avoids loading labels/vocab to a dict when not needed (e.g. for SentencePieces).
> Vocabulary, some refactor, more special labels 

- returnn/tf/data_pipeline.py
- returnn/tf/network.py
- tests/test_TFEngine.py
- tests/test_TFNetworkLayer.py
- tests/test_TFNetworkRecLayer.py
> batch_dim explicitly passed

- returnn/tf/data_pipeline.py
- returnn/tf/network.py
- tests/test_TFEngine.py
- tests/test_TFNetworkLayer.py
> feed dict backwards compatible, batch dim optional

- returnn/pretrain.py
- returnn/tf/engine.py
- returnn/theano/device.py
- returnn/util/basic.py
- tests/test_NetworkDescription.py
- tests/test_TFEngine.py
- tests/test_TFUtil.py
- tests/test_Util.py
- tools/analyze-dataset-batches.py
> Engine need_init_new_network, better comparison

- returnn/tf/layers/basic.py
- returnn/tf/layers/rec.py
Also make it much faster in case of exceptions,
to not keep trying again and again.
Related: #1129.
Fix #1127.
> Rec template construction simplify

- returnn/tf/util/data.py
- tests/test_TFUtil.py
Related, introduced via:
https://github.com/rwth-i6/returnn_common/issues/200
This is quite tricky...
> Dim declare_same_as fix is_dim_known logic

- docs/configuration_reference/behavior_version.rst
- returnn/tf/layers/basic.py
- returnn/tf/util/data.py
- returnn/util/basic.py
- tests/test_TFNetworkLayer.py
- tests/test_TFUtil.py
Fix #1154.
Fix https://github.com/rwth-i6/returnn_common/issues/227.
> DotLayer fix incorrect dim matching

- returnn/tf/layers/basic.py
- returnn/tf/network.py
- returnn/tf/util/data.py
- returnn/torch/engine.py
This PR has a couple of seemingly unrelated commits (so rebase instead of squash).
Anyway, it should fix #1167.
> Fix some Dim dyn_size_ext batch error

- returnn/datasets/basic.py
- returnn/datasets/cached.py
- returnn/datasets/cached2.py
- returnn/datasets/generating.py
- returnn/datasets/hdf.py
- returnn/datasets/numpy_dump.py
- returnn/datasets/sprint.py
> remove CTC targets from Datasets

- returnn/tf/engine.py
- returnn/util/basic.py
> restart_after_num_net_reinit option

- returnn/config.py
> remove devices_init_args() and multiprocessing parameter

- returnn/native_op.py
> remove unused destroy_map

- returnn/datasets/basic.py
- returnn/tf/engine.py
- tests/test_TFEngine.py
I removed the Theano branch and renamed the function to be more accurate. I think this is also relevant for any new backend as otherwise this function behaves incorrect.
> rework setting data definition from dataset

- returnn/tf/network.py
- returnn/tf/util/data.py
- returnn/util/basic.py
- tests/test_TFUtil.py
> Dim tags, reuse instances, avoid undefined

- returnn/tf/layers/basic.py
- returnn/tf/layers/rec.py
- returnn/tf/util/basic.py
Add global config option "inf_value" to the SelfAttentionLayer.
We need this to convert acoustic models to ONNX. The current value results in nan values.
> SelfAttentionLayer: add global inf_value option

- docs/configuration_reference/behavior_version.rst
- returnn/tf/layers/rec.py
- returnn/tf/util/data.py
- returnn/util/basic.py
- tests/test_TFNetworkLayer.py
- tests/test_TFNetworkRecLayer.py
Fix https://github.com/rwth-i6/returnn/issues/865.
Fix https://github.com/rwth-i6/returnn/issues/1219.
Alternative to #1220.
As you see in the commits, there are some rare cases where it breaks some user configs. Thus I introduced a new behavior version.
> Dim is_equal, check auto_generated

- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
Implemented 1d convolution with striding and dilation
@vieting
> ConvLayer, support 1d conv with striding and dilation

- returnn/tf/util/basic.py
I guess just copy/paste error.
> optional_mul: fix docstring

- returnn/datasets/lm.py
Fix for #1245 
Should not break old behavior, as for correct bijective mappings this results in the same sizes, and surjective mappings gave wrong sizes, resulting in models which I assume nobody could use correctly.
> LmDataset fix `labels`

- returnn/datasets/basic.py
@sarahberanek Can you try? Should be all that is needed to get seq_tags_filter working again.
> get_seq_order_for_epoch: fix seq_tags_filter

- returnn/tf/layers/basic.py
- returnn/tf/layers/rec.py
- returnn/tf/util/data.py
- tests/test_TFNetworkLayer.py
- tests/test_TFNetworkRecLayer.py
> RelativePositionalEncodingLayer, fix dyn dim tag dyn_size_ext template

- .github/workflows/main.yml
- returnn/frontend_api.py
- returnn/tf/frontend_low_level/frontend.py
- returnn/torch/frontend/_internal_frontend.py
- returnn/torch/frontend/frontend.py
- tests/test_torch_frontend.py
Making this a pull request because I added a new test module, want to make sure it is executed correctly.
Also, there are probably things to discuss. 🙃 
So, I added `dot()` to `Frontend` and implemented it for the `TorchFrontend`. It seems to work for pretty much all cases, see the tests.
Masking is still missing as I didn't understand the implementation in DotLayer right away, will look into it... Also, as discussed, handling sparse inputs is not yet implemented.
> TorchFrontend: dot product

- returnn/tensor/_tensor_extra.py
- returnn/tensor/tensor.py
Fix #1273.
This is also to prepare for https://github.com/rwth-i6/returnn_common/issues/252.
> allow Tensor feature_dim_axis, add feature_dim

- .github/workflows/main.yml
- returnn/_internal_frontend_api.py
- returnn/frontend_api.py
- returnn/tensor/_tensor_extra.py
- returnn/tf/frontend_low_level/_internal_frontend.py
- returnn/torch/frontend/_internal_frontend.py
- returnn/torch/frontend/frontend.py
- tests/test_torch_internal_frontend.py
Creates `combine()`, handles tensor operations (e.g. Tensor + Tensor), and some more improvements.
> Frontend combine, tensor ops

- returnn/engine/base.py
- returnn/tf/engine.py
- returnn/torch/engine.py
learning rate handling is the same for TF and PT.
> unify learning rates in EngineBase

- returnn/learning_rate_control.py
Returnn should try to create the folder for the learning-rates file location if not existing yet.
> use os.makedirs for learning rates file

- returnn/torch/engine.py
Also @Icemole @patrick-wilken, I would prefer to write `train_loss_<name>` and `dev_loss_<name>` instead of `score`, what is your opinion on that?
> add training losses to learning rates file

- returnn/tensor/_tensor_extra.py
- tests/_setup_test_env.py
- tests/test_TFUtil.py
> Tensor, fix TF dependency via batch dim

- returnn/tf/engine.py
> tf engine compute priors fix batch size

- tests/_setup_test_env.py
- tests/test_demos.py
> PyTorch ONNX export test

- returnn/tf/layers/rec.py
- tests/test_TFNetworkRecLayer.py
See #1248.
This makes #1248 obsolete.
> TF initial state placeholder, add identity

- returnn/tf/layers/rec.py
- tests/test_TFNetworkRecLayer.py
See #1248.
Specifically for `SelfAttentionLayer`.
> TF rec initial state fix last state var, placeholder

- returnn/tensor/_dim_extra.py
- returnn/tensor/_tensor_extra.py
- returnn/tf/network.py
- returnn/util/basic.py
- tests/test_TFNetworkLayer.py
Some other commits alongside (I suggest to merge, not to squash).
> Tensor, fix time flattened with scalar dyn size

- .github/workflows/main.yml
- returnn/frontend/__init__.py
- returnn/frontend/_backend.py
- returnn/frontend/gradient.py
- returnn/frontend/label_smoothing.py
- returnn/tf/frontend_layers/_backend.py
- returnn/tf/layers/basic.py
- returnn/torch/frontend/_backend.py
- returnn/torch/functional/scaled_gradient.py
- tests/test_rf_gradient.py
- tests/test_rf_label_smoothing.py
I suggest to merge, not to squash.
> RF label smoothing, gradient, scaled gradient

- returnn/tf/layers/rec.py
- tests/test_TFNetworkRecLayer.py
This fixes the case when inside masked computation.
> TF PositionalEncodingLayer inside rec, position state

- returnn/tensor/_dim_extra.py
- returnn/tensor/_tensor_extra.py
- returnn/tf/layers/basic.py
- returnn/tf/util/data.py
Extracted from #1393, which we are probably not merging like this, some random commits which still seems useful.
Intended for rebase, not squash.
> Batch info better

- returnn/frontend/_backend.py
- returnn/frontend/_native/__init__.py
- returnn/frontend/_numpy_backend.py
- returnn/frontend/_utils.py
- returnn/tensor/_dim_extra.py
- returnn/tensor/_tensor_extra.py
- returnn/torch/frontend/_backend.py
- tests/rf_utils.py
And a few other semi-related changes.
I suggest to merge this PR, not squash, as it's only semi-related, but also independent.
> Tensor copy_compatible_to_dims and optimizations

- returnn/frontend/_backend.py
- returnn/frontend/run_ctx.py
- returnn/tf/frontend_layers/_backend.py
- returnn/tf/layers/base.py
> RF backend make_output_tensor, TF-layers disallow transpose

- returnn/frontend/__init__.py
- returnn/frontend/_backend.py
- returnn/frontend/_native/tensor_ops.cpp
- returnn/frontend/_utils.py
- returnn/frontend/backend.py
- returnn/tensor/_dim_extra.py
- returnn/tf/frontend_layers/_backend.py
- tests/rf_utils.py
- tests/test_rf_base.py
For #1402.
Also important follow-up fix for #1416.
There are a few somewhat unrelated commits, so I suggest to merge, not squash.
> Dim seq mask cache across copy_from

- returnn/tensor/_dim_extra.py
- returnn/tensor/tensor_dict.py
- returnn/tf/frontend_layers/config_entry_points.py
- tests/rf_utils.py
Needed for #1418.
I would suggest to merge instead of squash, as the commits are somewhat individual.
(Although, previous attempts to submit them more individually caused failing tests, e.g. #1422, so I don't do that now.)
> Dim reset better for math cache

- returnn/tensor/_dim_extra.py
> Dim math caching better

- tools/compile_native_op.py
> compile_native_op: consider only TensorFlow ops

- returnn/util/basic.py
- returnn/util/multi_proc_non_daemonic_spawn.py
- tests/test_Util.py
> NonDaemonicSpawnProcess custom pre_init_func, fix parent hang

- LICENSE
- returnn/config.py
- returnn/datasets/basic.py
- returnn/datasets/cached.py
- returnn/datasets/cached2.py
- returnn/datasets/concat_files.py
- returnn/datasets/generating.py
- returnn/datasets/hdf.py
- returnn/datasets/multi_proc.py
- returnn/torch/data/pipeline.py
- returnn/util/basic.py
- returnn/util/file_cache.py
- tests/test_Dataset.py
- tests/test_HDFDataset.py
- tests/test_Util.py
> ConcatFilesDataset

- returnn/datasets/concat_files.py
- tests/test_Dataset.py
> Make `ConcatFilesDataset` compatible with multimodal data

- returnn/datasets/basic.py
- returnn/datasets/distrib_files.py
- tests/test_Dataset.py
Closes #1535, using Albert's proposal that got two :+1: 
@Icemole this is a breaking change, which we deemed ok because nobody's got a real setup with this dataset yet
> Rename `ConcatFilesDataset` to `DistributeFilesDataset`

- returnn/datasets/basic.py
- returnn/datasets/distrib_files.py
- tests/test_Dataset.py
Closes #1531.
See PR #1521 for the initial implementation, and issue #1519 for the initial discussion on `DistributeFilesDataset`.
> `DistributeFilesDataset`: allow sharding files across GPU workers

- returnn/util/file_cache.py
testing if this makes a difference...
Closes #1542
> `FileCache`: retry on ENOSPC, prealloc space, lock on whole cache dir

- returnn/util/file_cache.py
* Closes #1547
* Closes #1548 
* Closes #1550
> FileCache reliability improvements

- returnn/datasets/distrib_files.py
> DistributeFilesDataset: pass worker group info from parent process to child via pickle

- .github/workflows/main.yml
- returnn/datasets/generating.py
- returnn/datasets/util/feature_extraction.py
- returnn/sprint/control.py
- returnn/sprint/interface.py
- returnn/tf/data_pipeline.py
- returnn/tf/hyper_param_tuning.py
- returnn/tf/layers/rec.py
- returnn/tf/layers/signal_processing.py
- returnn/tf/native_op.py
- returnn/tf/updater.py
- returnn/tf/util/basic.py
- returnn/tf/util/data.py
- returnn/util/basic.py
- returnn/util/better_exchook.py
- returnn/util/debug.py
- tools/tf_inspect_checkpoint.py
- tools/torch_inspect_checkpoint.py
Needed for example for #1559 but useful in general to update this.
Not so happy with many of the false positive warning reports but this is mostly due to Scipy/Numpy and nothing really we can fix on our side.
> CI PyCharm update Torch

- returnn/torch/data/pipeline.py
- tests/test_torch_engine.py
Closes #1560 
This is a pretty small, but significant change, so I did make this into a PR and did not directly commit to master.
> Default torch DataLoader num_workers to 1

- returnn/frontend/array_.py
- returnn/frontend/math_.py
> RF sequence_mask for more dyn dims

- returnn/torch/frontend/_backend.py
- returnn/torch/util/array_.py
- tests/test_torch_frontend.py
- tests/torch_utils.py
> Optimize RF PT pack_padded

- returnn/util/file_cache.py
- tests/test_Util.py
...by storing the `mtime`s in dedicated keepalive files next to the cached files themselves.
Closes #1602 
@Icemole Do you want to test this in your setup?
> `FileCache`: detect modified source files

- tools/bliss-to-ogg-zip.py
Closes https://github.com/rwth-i6/i6_experiments/pull/248
> Simplify assertion in bliss-to-ogg-zip tool

- returnn/tf/layers/base.py
- returnn/tf/layers/basic.py
- tests/test_TFNetworkLayer.py
Found via #1616 (but it does not fix the problem itself).
> TF fix combined variational noise and weight dropout

- returnn/tf/util/gradient_checkpoint.py
> TF prepare_gradient_checkpointing, fix for newer TF

- returnn/torch/engine.py
Like #1627, but w/ the data assignment fix applied.
Closes #1621
> PT: regularly sync progress during eval, fix tensor assignment

- returnn/datasets/postprocessing.py
> `LaplaceOrdering`: avoid spiky CPU utilization

- returnn/tensor/_dim_extra.py
- tests/test_rf_base.py
(Also a bit of a reminder for #975...)
> Dim declare_same_as, fix when existing same_as

- returnn/datasets/audio.py
- returnn/datasets/basic.py
- returnn/datasets/cached.py
- returnn/datasets/distrib_files.py
- returnn/datasets/generating.py
- returnn/datasets/hdf.py
- returnn/datasets/lm.py
- returnn/datasets/meta.py
- returnn/datasets/multi_proc.py
- returnn/datasets/postprocessing.py
- returnn/datasets/sprint.py
- tests/test_MultiProcDataset.py
This PR adds support for within-dataset sharding, allowing e.g. the use of `MultiProcDataset` wrapping a `PostprocessingDataset`.
> Datasets: implement support for within-dataset sharding

- docs/configuration_reference/behavior_version.rst
- returnn/frontend/_cache.py
- returnn/frontend/_native/__init__.py
- returnn/frontend/_random_journal.py
- returnn/frontend/conv.py
- returnn/frontend/dims.py
- returnn/frontend/rec.py
- returnn/frontend/run_ctx.py
- returnn/tensor/_dim_extra.py
- returnn/tensor/_tensor_extra.py
- returnn/tensor/_tensor_op_overloads.py
- returnn/tensor/dim.py
- returnn/tensor/tensor_dict.py
- returnn/tf/frontend_layers/_backend.py
- returnn/tf/frontend_layers/dims.py
- returnn/tf/frontend_layers/layer.py
- returnn/tf/frontend_layers/loop.py
- returnn/tf/frontend_layers/make_layer.py
- returnn/tf/frontend_layers/prev_tensor_ref.py
- returnn/tf/frontend_low_level/_backend.py
- returnn/tf/layers/base.py
- returnn/tf/layers/basic.py
- returnn/tf/layers/rec.py
- returnn/tf/network.py
- returnn/torch/data/extern_data.py
- returnn/util/basic.py
- tests/rf_utils.py
- tests/test_TFUtil.py
- tools/compile_tf_graph.py
- tools/torch_export_to_onnx.py
> Tensor, disallow __bool__

- returnn/frontend/_backend.py
- returnn/frontend/array_.py
- returnn/tf/frontend_layers/_backend.py
- returnn/torch/frontend/_backend.py
> RF merge_dims, fix for mult dyn dims

- returnn/frontend/audio/specaugment.py
- returnn/frontend/dropout.py
- returnn/frontend/normalization.py
- returnn/frontend/parametrizations.py
- returnn/frontend/rec.py
- returnn/frontend/reduce.py
- returnn/frontend/run_ctx.py
- returnn/torch/frontend/_backend.py
- tests/test_rf_base.py
> RF RunCtx train_flag per func

- returnn/util/basic.py
- returnn/util/file_cache.py
@hannah220 Can you try out this PR?
Maybe a fix for #1675
> FileCache: hold lock and refresh mtime during cleanup

- returnn/datasets/basic.py
> get_complete_frac fix when num_seqs is None

- returnn/torch/distributed.py
- returnn/torch/engine.py
> PT: in param avg, only sync data every sync step

- returnn/datasets/distrib_files.py
- returnn/datasets/multi_proc.py
When the buffer is full and the next seq is loaded from the subproc, the previous list-based implementation needed to move `buf_size - 1` elements in the buffer (O(n)) while for the deque, this operation is O(1). These buffers can be large (I usually use `N` around `max_seqs < N < 10 * max_seqs`), so I believe it's good we use efficient algorithms there.
I decided to postpone also adjusting the implementation of `CachedDataset2`. I believe the cache list in that dataset doesn't grow very large usually (I think at least for torch trainings there is only ever going to be one element in the cache?), so it's okay if it's not as asymptotically efficient (also asymptotically less efficient algorithms can still be efficient on small lists). Also, there are some derived datasets that access and …
> MPD, DFD: use deque as cache impl for better efficiency

- returnn/torch/updater.py
- tests/test_torch_engine.py
See `test_updater_lr_multipliers` for a practical example.
> PT updater, support learning_rate_multiplier per param group

- returnn/frontend/nested.py
- tests/test_rf_decoder_transformer.py
See #1759 for some discussion.
> RF nested masked_scatter, extra check for dim consistency
